<a href="https://colab.research.google.com/github/dinuka-rp/nerdy-panda/blob/main/Prototype/RecSys/Trends_Content_based_NFT_Recommender_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Trends Content-based NFT Recommender System

https://towardsdatascience.com/how-to-build-from-scratch-a-content-based-movie-recommender-with-natural-language-processing-25ad400eb243

Check this later (not that different): https://medium.com/dataseries/recommendation-system-in-python-4d4cf6d33166 , https://gist.github.com/deansublett/06f010a886831f9dac5b1f9bce4f4229?source=post_page---------------------------

In [83]:
!pip install rake-nltk
!pip install pymongo
!pip install dnspython

Requirement already satisfied: rake-nltk in /usr/local/lib/python3.7/dist-packages (1.0.6)
Requirement already satisfied: nltk<4.0.0,>=3.6.2 in /usr/local/lib/python3.7/dist-packages (from rake-nltk) (3.7)
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from nltk<4.0.0,>=3.6.2->rake-nltk) (7.1.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from nltk<4.0.0,>=3.6.2->rake-nltk) (1.1.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.7/dist-packages (from nltk<4.0.0,>=3.6.2->rake-nltk) (2022.3.15)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from nltk<4.0.0,>=3.6.2->rake-nltk) (4.64.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.7/dist-packages (4.1.0)
Requirement already satisfied: dnspython in /usr/local/lib/python3.7/dist-packages (2.2.1)

In [84]:
import pandas as pd
from rake_nltk import Rake
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
import nltk
from datetime import datetime, date

nltk.download('stopwords')
from nltk.corpus import stopwords
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

## Get Dataset

### NFT Data

In [85]:
from google.colab import drive
drive.mount('drive')

assets_file_path = "/content/drive/MyDrive/Datasets/FYP/collected-nft-assets"
df = pd.read_csv(assets_file_path, sep='\t')

# df = df[['nft_id','traits_string','asset_contract_address', 'total_rarity']]
df.head()

Drive already mounted at drive; to attempt to forcibly remount, call drive.mount("drive", force_remount=True).

,nft_id,name,asset_description,asset_contract_address,collection_name,collection_description,collection_slug,collection_verification,creator_username,creator_address,...,owner_profile_img_url,traits_string,total_rarity,num_sales,last_sale_timestamp,last_sale_total_price,last_sale_from_account_address,top_bid,open_sea_link,image_url
0,2541585283815458503018281017495372409420154545...,CelebCard #84 Snoop Dogg,NaN,0x495f947276749ce646f68ac8c248420045cb7b5e,Mesmerizer,No theme. No traits. No rules. A treasure trov...,mesmerizer,False,NaN,0x3830dce8b8f5543404e005776b4de22870c01d64,...,https://storage.googleapis.com/opensea-static/...,NaN,0.0,0,NaN,NaN,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/DwknciiKsguS...
1,4460258260744616717349398633449740654585409544...,3D Penguin Planet Official Collection,3D Penguin Planet Collection It was hand paint...,0x495f947276749ce646f68ac8c248420045cb7b5e,3D Penguin Planet Official Collection,3D Penguin Planet Official Collection It was h...,3d-penguin-planet-official-collection,False,NaN,0x629c2ac970da51a3fa29af4015e06c250c267e36,...,https://storage.googleapis.com/opensea-static/...,NaN,0.0,0,NaN,NaN,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/yzniUTh85SYY...
2,1143238369460653929904223751867794581426030911...,VECTOR KAS 10 (The Relax),VECTOR KAS 10,0x495f947276749ce646f68ac8c248420045cb7b5e,Kalvintaka Collection,NaN,kalvintaka-collection,False,Creative_FineArts_and_Designs,0xfcc0ffa7b48f9af939ed6e9d3c535e371ab2f17f,...,https://storage.googleapis.com/opensea-static/...,NaN,0.0,0,NaN,NaN,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/2xDLW3Nrrt8u...
3,5742295951199733757787373026863398866922647154...,Gooniez #1989,"A gang of 8,888 gooniez unleashed to wreak hav...",0x495f947276749ce646f68ac8c248420045cb7b5e,Metaverse GooniezNFT,"A gang of 8,888 gooniez unleashed to wreak hav...",metaverse-goonieznft,False,GooniezNFTCollection,0x7ef43e4a20315830feacb23fe17f7cf2d49f2491,...,https://storage.googleapis.com/opensea-static/...,NaN,0.0,0,NaN,NaN,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/Y4lDr3FzA7xm...
4,1006254684714400059060824656421626037946389019...,Darumaa Soul Story.#3,Works that are created by an Extraterrestrial ...,0x495f947276749ce646f68ac8c248420045cb7b5e,Extraterrestrial Soul Darumaa,Darumaa. Not Real & Reality.\n\nWorks that are...,darumaa,False,FRABATO,0xde77ff31b3601243b0f41441e1f015456b2b1ad2,...,https://storage.googleapis.com/opensea-static/...,NaN,0.0,0,NaN,NaN,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/9xcm5vesaQYE...

### Twitter Auth Token

In [86]:
auth_token = "AAAAAAAAAAAAAAAAAAAAAEAvTAEAAAAAQeWT9FEvcpxz3Ebg5IS45oASCjM%3DT67USoXi0iCtPoLRMHpDGQw3unxzJlEXHY2CZWR04UcCvtTcmn"

### Trends Data

In [87]:
import requests

def fetch_twitter_trends(woeid=1):

  url = "https://api.twitter.com/1.1/trends/place.json?id=" + str(woeid)

  payload={}
  headers = {
    'Authorization': 'Bearer ' + auth_token,
    'Cookie': 'guest_id=v1%3A164302265238123185; guest_id_ads=v1%3A164302265238123185; guest_id_marketing=v1%3A164302265238123185; personalization_id="v1_7SOW+P3aER3WzxCMuCXiWw=="'
  }

  response = requests.request("GET", url, headers=headers, data=payload)

  if response.status_code != 200:
    print('error')

  trends = response.json()[0]['trends']
  # print(trends)
  return trends

twitter_trends = fetch_twitter_trends()
# twitter_trends = fetch_twitter_trends(woeid=2282863)

print(twitter_trends)

[{'name': 'Happy Easter', 'url': 'http://twitter.com/search?q=%22Happy+Easter%22', 'promoted_content': None, 'query': '%22Happy+Easter%22', 'tweet_volume': 796757}, {'name': '#V最協S4', 'url': 'http://twitter.com/search?q=%23V%E6%9C%80%E5%8D%94S4', 'promoted_content': None, 'query': '%23V%E6%9C%80%E5%8D%94S4', 'tweet_volume': 85260}, {'name': '#鎌倉殿の13人', 'url': 'http://twitter.com/search?q=%23%E9%8E%8C%E5%80%89%E6%AE%BF%E3%81%AE13%E4%BA%BA', 'promoted_content': None, 'query': '%23%E9%8E%8C%E5%80%89%E6%AE%BF%E3%81%AE13%E4%BA%BA', 'tweet_volume': 33141}, {'name': '#STAWIN', 'url': 'http://twitter.com/search?q=%23STAWIN', 'promoted_content': None, 'query': '%23STAWIN', 'tweet_volume': 55228}, {'name': '#냥냥즈에게_물어봐', 'url': 'http://twitter.com/search?q=%23%EB%83%A5%EB%83%A5%EC%A6%88%EC%97%90%EA%B2%8C_%EB%AC%BC%EC%96%B4%EB%B4%90', 'promoted_content': None, 'query': '%23%EB%83%A5%EB%83%A5%EC%A6%88%EC%97%90%EA%B2%8C_%EB%AC%BC%EC%96%B4%EB%B4%90', 'tweet_volume': 28349}, {'name': 'Buona Pasqua', 'url': 'http://twitter.com/search?q=%22Buona+Pasqua%22', 'promoted_content': None, 'query': '%22Buona+Pasqua%22', 'tweet_volume': 81024}, {'name': '#QEDWIN', 'url': 'http://twitter.com/search?q=%23QEDWIN', 'promoted_content': None, 'query': '%23QEDWIN', 'tweet_volume': 57358}, {'name': 'Frohe Ostern', 'url': 'http://twitter.com/search?q=%22Frohe+Ostern%22', 'promoted_content': None, 'query': '%22Frohe+Ostern%22', 'tweet_volume': 33808}, {'name': 'Feliz Páscoa', 'url': 'http://twitter.com/search?q=%22Feliz+P%C3%A1scoa%22', 'promoted_content': None, 'query': '%22Feliz+P%C3%A1scoa%22', 'tweet_volume': 32656}, {'name': '2NE1', 'url': 'http://twitter.com/search?q=2NE1', 'promoted_content': None, 'query': '2NE1', 'tweet_volume': 1518103}, {'name': 'Pâques', 'url': 'http://twitter.com/search?q=P%C3%A2ques', 'promoted_content': None, 'query': 'P%C3%A2ques', 'tweet_volume': 75558}, {'name': '佐々木朗希', 'url': 'http://twitter.com/search?q=%E4%BD%90%E3%80%85%E6%9C%A8%E6%9C%97%E5%B8%8C', 'promoted_content': None, 'query': '%E4%BD%90%E3%80%85%E6%9C%A8%E6%9C%97%E5%B8%8C', 'tweet_volume': 116992}, {'name': 'ニジマス解散', 'url': 'http://twitter.com/search?q=%E3%83%8B%E3%82%B8%E3%83%9E%E3%82%B9%E8%A7%A3%E6%95%A3', 'promoted_content': None, 'query': '%E3%83%8B%E3%82%B8%E3%83%9E%E3%82%B9%E8%A7%A3%E6%95%A3', 'tweet_volume': None}, {'name': 'BTS IS COMING', 'url': 'http://twitter.com/search?q=%22BTS+IS+COMING%22', 'promoted_content': None, 'query': '%22BTS+IS+COMING%22', 'tweet_volume': 329546}, {'name': 'He is Risen', 'url': 'http://twitter.com/search?q=%22He+is+Risen%22', 'promoted_content': None, 'query': '%22He+is+Risen%22', 'tweet_volume': 56190}, {'name': 'Mr Speaker', 'url': 'http://twitter.com/search?q=%22Mr+Speaker%22', 'promoted_content': None, 'query': '%22Mr+Speaker%22', 'tweet_volume': 19941}, {'name': 'BTS COMEBACK', 'url': 'http://twitter.com/search?q=%22BTS+COMEBACK%22', 'promoted_content': None, 'query': '%22BTS+COMEBACK%22', 'tweet_volume': 411894}, {'name': 'WE ARE BULLETPROOF', 'url': 'http://twitter.com/search?q=%22WE+ARE+BULLETPROOF%22', 'promoted_content': None, 'query': '%22WE+ARE+BULLETPROOF%22', 'tweet_volume': 382725}, {'name': 'アナグマ', 'url': 'http://twitter.com/search?q=%E3%82%A2%E3%83%8A%E3%82%B0%E3%83%9E', 'promoted_content': None, 'query': '%E3%82%A2%E3%83%8A%E3%82%B0%E3%83%9E', 'tweet_volume': None}, {'name': 'マミちゃん', 'url': 'http://twitter.com/search?q=%E3%83%9E%E3%83%9F%E3%81%A1%E3%82%83%E3%82%93', 'promoted_content': None, 'query': '%E3%83%9E%E3%83%9F%E3%81%A1%E3%82%83%E3%82%93', 'tweet_volume': None}, {'name': 'イッテQ', 'url': 'http://twitter.com/search?q=%E3%82%A4%E3%83%83%E3%83%86Q', 'promoted_content': None, 'query': '%E3%82%A4%E3%83%83%E3%83%86Q', 'tweet_volume': None}, {'name': "P'Jack", 'url': 'http://twitter.com/search?q=P%27Jack', 'promoted_content': None, 'query': 'P%27Jack', 'tweet_volume': None}, {'name': 'V最協見', 'url': 'http://twitter.com/search?q=V%E6%9C%80%E5%8D%94%E8%A6%8B', 'promoted_content': None, 'query': 'V%E6%9C%80%E5%8D%94%E8%A6%8B', 'tweet_volume': None}, {'name': 'Isko', 'url': 'http://twitter.com/search?q=Isko', 'promoted_content': None, 'query': 'Isko', 'tweet_volume': 148815}, {'name': 'イースター', 'url': 'http://twitter.com/search?q=%E3%82%A4%E3%83%BC%E3%82%B9%E3%82%BF%E3%83%BC', 'promoted_content': None, 'query': '%E3%82%A4%E3%83%BC%E3%82%B9%E3%82%BF%E3%83%BC', 'tweet_volume': 169129}, {'name': 'Domingo de Resurrección', 'url': 'http://twitter.com/search?q=%22Domingo+de+Resurrecci%C3%B3n%22', 'promoted_content': None, 'query': '%22Domingo+de+Resurrecci%C3%B3n%22', 'tweet_volume': 26737}, {'name': 'すわほー', 'url': 'http://twitter.com/search?q=%E3%81%99%E3%82%8F%E3%81%BB%E3%83%BC', 'promoted_content': None, 'query': '%E3%81%99%E3%82%8F%E3%81%BB%E3%83%BC', 'tweet_volume': None}, {'name': '善児の名前', 'url': 'http://twitter.com/search?q=%E5%96%84%E5%85%90%E3%81%AE%E5%90%8D%E5%89%8D', 'promoted_content': None, 'query': '%E5%96%84%E5%85%90%E3%81%AE%E5%90%8D%E5%89%8D', 'tweet_volume': None}, {'name': 'Daisuke', 'url': 'http://twitter.com/search?q=Daisuke', 'promoted_content': None, 'query': 'Daisuke', 'tweet_volume': 11957}, {'name': 'Taka', 'url': 'http://twitter.com/search?q=Taka', 'promoted_content': None, 'query': 'Taka', 'tweet_volume': 64176}, {'name': '石田さん', 'url': 'http://twitter.com/search?q=%E7%9F%B3%E7%94%B0%E3%81%95%E3%82%93', 'promoted_content': None, 'query': '%E7%9F%B3%E7%94%B0%E3%81%95%E3%82%93', 'tweet_volume': None}, {'name': 'Zanzibar', 'url': 'http://twitter.com/search?q=Zanzibar', 'promoted_content': None, 'query': 'Zanzibar', 'tweet_volume': 178754}, {'name': 'Osterfest', 'url': 'http://twitter.com/search?q=Osterfest', 'promoted_content': None, 'query': 'Osterfest', 'tweet_volume': None}, {'name': '井口監督', 'url': 'http://twitter.com/search?q=%E4%BA%95%E5%8F%A3%E7%9B%A3%E7%9D%A3', 'promoted_content': None, 'query': '%E4%BA%95%E5%8F%A3%E7%9B%A3%E7%9D%A3', 'tweet_volume': 13009}, {'name': 'Startend', 'url': 'http://twitter.com/search?q=Startend', 'promoted_content': None, 'query': 'Startend', 'tweet_volume': 56647}, {'name': 'Vrolijk Pasen', 'url': 'http://twitter.com/search?q=%22Vrolijk+Pasen%22', 'promoted_content': None, 'query': '%22Vrolijk+Pasen%22', 'tweet_volume': None}, {'name': 'ダービー', 'url': 'http://twitter.com/search?q=%E3%83%80%E3%83%BC%E3%83%93%E3%83%BC', 'promoted_content': None, 'query': '%E3%83%80%E3%83%BC%E3%83%93%E3%83%BC', 'tweet_volume': 26529}, {'name': 'どらほー', 'url': 'http://twitter.com/search?q=%E3%81%A9%E3%82%89%E3%81%BB%E3%83%BC', 'promoted_content': None, 'query': '%E3%81%A9%E3%82%89%E3%81%BB%E3%83%BC', 'tweet_volume': None}, {'name': '당신의 19금 성향', 'url': 'http://twitter.com/search?q=%22%EB%8B%B9%EC%8B%A0%EC%9D%98+19%EA%B8%88+%EC%84%B1%ED%96%A5%22', 'promoted_content': None, 'query': '%22%EB%8B%B9%EC%8B%A0%EC%9D%98+19%EA%B8%88+%EC%84%B1%ED%96%A5%22', 'tweet_volume': None}, {'name': '#しらんでぇWIN', 'url': 'http://twitter.com/search?q=%23%E3%81%97%E3%82%89%E3%82%93%E3%81%A7%E3%81%87WIN', 'promoted_content': None, 'query': '%23%E3%81%97%E3%82%89%E3%82%93%E3%81%A7%E3%81%87WIN', 'tweet_volume': 11482}, {'name': '#鉄腕DASH', 'url': 'http://twitter.com/search?q=%23%E9%89%84%E8%85%95DASH', 'promoted_content': None, 'query': '%23%E9%89%84%E8%85%95DASH', 'tweet_volume': 13776}, {'name': '#ales2022', 'url': 'http://twitter.com/search?q=%23ales2022', 'promoted_content': None, 'query': '%23ales2022', 'tweet_volume': None}, {'name': '#フロイニ', 'url': 'http://twitter.com/search?q=%23%E3%83%95%E3%83%AD%E3%82%A4%E3%83%8B', 'promoted_content': None, 'query': '%23%E3%83%95%E3%83%AD%E3%82%A4%E3%83%8B', 'tweet_volume': 257105}, {'name': '#SNDWIN', 'url': 'http://twitter.com/search?q=%23SNDWIN', 'promoted_content': None, 'query': '%23SNDWIN', 'tweet_volume': None}, {'name': '#RIZIN35', 'url': 'http://twitter.com/search?q=%23RIZIN35', 'promoted_content': None, 'query': '%23RIZIN35', 'tweet_volume': 30054}, {'name': '#地球しか勝たん', 'url': 'http://twitter.com/search?q=%23%E5%9C%B0%E7%90%83%E3%81%97%E3%81%8B%E5%8B%9D%E3%81%9F%E3%82%93', 'promoted_content': None, 'query': '%23%E5%9C%B0%E7%90%83%E3%81%97%E3%81%8B%E5%8B%9D%E3%81%9F%E3%82%93', 'tweet_volume': 53713}, {'name': '#スクフェス9周年', 'url': 'http://twitter.com/search?q=%23%E3%82%B9%E3%82%AF%E3%83%95%E3%82%A7%E3%82%B99%E5%91%A8%E5%B9%B4', 'promoted_content': None, 'query': '%23%E3%82%B9%E3%82%AF%E3%83%95%E3%82%A7%E3%82%B99%E5%91%A8%E5%B9%B4', 'tweet_volume': None}, {'name': '#2ndPREMIUMLIVE_B_DAY3', 'url': 'http://twitter.com/search?q=%232ndPREMIUMLIVE_B_DAY3', 'promoted_content': None, 'query': '%232ndPREMIUMLIVE_B_DAY3', 'tweet_volume': 386395}, {'name': '#ジャンクSPORTS', 'url': 'http://twitter.com/search?q=%23%E3%82%B8%E3%83%A3%E3%83%B3%E3%82%AFSPORTS', 'promoted_content': None, 'query': '%23%E3%82%B8%E3%83%A3%E3%83%B3%E3%82%AFSPORTS', 'tweet_volume': 17517}, {'name': '#TurgutÖzal', 'url': 'http://twitter.com/search?q=%23Turgut%C3%96zal', 'promoted_content': None, 'query': '%23Turgut%C3%96zal', 'tweet_volume': 12334}]

In [88]:
twitter_trends = [{'name': '#โหนกระเเส', 'url': 'http://twitter.com/search?q=%23%E0%B9%82%E0%B8%AB%E0%B8%99%E0%B8%81%E0%B8%A3%E0%B8%B0%E0%B9%80%E0%B9%80%E0%B8%AA', 'promoted_content': None, 'query': '%23%E0%B9%82%E0%B8%AB%E0%B8%99%E0%B8%81%E0%B8%A3%E0%B8%B0%E0%B9%80%E0%B9%80%E0%B8%AA', 'tweet_volume': 2166180}, {'name': '#Euphoria', 'url': 'http://twitter.com/search?q=%23Euphoria', 'promoted_content': None, 'query': '%23Euphoria', 'tweet_volume': 1005172}, {'name': 'Cassie', 'url': 'http://twitter.com/search?q=Cassie', 'promoted_content': None, 'query': 'Cassie', 'tweet_volume': 416023}, {'name': 'Maddy', 'url': 'http://twitter.com/search?q=Maddy', 'promoted_content': None, 'query': 'Maddy', 'tweet_volume': 352427}, {'name': '#28Şubat', 'url': 'http://twitter.com/search?q=%2328%C5%9Eubat', 'promoted_content': None, 'query': '%2328%C5%9Eubat', 'tweet_volume': 42633}, {'name': 'Elliot', 'url': 'http://twitter.com/search?q=Elliot', 'promoted_content': None, 'query': 'Elliot', 'tweet_volume': 231872}, {'name': 'Andalucía', 'url': 'http://twitter.com/search?q=Andaluc%C3%ADa', 'promoted_content': None, 'query': 'Andaluc%C3%ADa', 'tweet_volume': 39283}, {'name': '#MondayMotivation', 'url': 'http://twitter.com/search?q=%23MondayMotivation', 'promoted_content': None, 'query': '%23MondayMotivation', 'tweet_volume': 23904}, {'name': 'Lexi', 'url': 'http://twitter.com/search?q=Lexi', 'promoted_content': None, 'query': 'Lexi', 'tweet_volume': 246787}, {'name': '#Callin_MV_Out', 'url': 'http://twitter.com/search?q=%23Callin_MV_Out', 'promoted_content': None, 'query': '%23Callin_MV_Out', 'tweet_volume': 23107}, {'name': 'Lakers', 'url': 'http://twitter.com/search?q=Lakers', 'promoted_content': None, 'query': 'Lakers', 'tweet_volume': 89051}, {'name': 'Larissa', 'url': 'http://twitter.com/search?q=Larissa', 'promoted_content': None, 'query': 'Larissa', 'tweet_volume': 329769}, {'name': 'Jules', 'url': 'http://twitter.com/search?q=Jules', 'promoted_content': None, 'query': 'Jules', 'tweet_volume': 100974}, {'name': 'sam levinson', 'url': 'http://twitter.com/search?q=%22sam+levinson%22', 'promoted_content': None, 'query': '%22sam+levinson%22', 'tweet_volume': 93293}, {'name': 'Faye', 'url': 'http://twitter.com/search?q=Faye', 'promoted_content': None, 'query': 'Faye', 'tweet_volume': 107648}, {'name': 'Nate', 'url': 'http://twitter.com/search?q=Nate', 'promoted_content': None, 'query': 'Nate', 'tweet_volume': 137511}, {'name': 'Toz Taneleri', 'url': 'http://twitter.com/search?q=%22Toz+Taneleri%22', 'promoted_content': None, 'query': '%22Toz+Taneleri%22', 'tweet_volume': None}, {'name': "NU'EST", 'url': 'http://twitter.com/search?q=NU%27EST', 'promoted_content': None, 'query': 'NU%27EST', 'tweet_volume': 13042}, {'name': '政策金利', 'url': 'http://twitter.com/search?q=%E6%94%BF%E7%AD%96%E9%87%91%E5%88%A9', 'promoted_content': None, 'query': '%E6%94%BF%E7%AD%96%E9%87%91%E5%88%A9', 'tweet_volume': None}, {'name': '非核三原則', 'url': 'http://twitter.com/search?q=%E9%9D%9E%E6%A0%B8%E4%B8%89%E5%8E%9F%E5%89%87', 'promoted_content': None, 'query': '%E9%9D%9E%E6%A0%B8%E4%B8%89%E5%8E%9F%E5%89%87', 'tweet_volume': None}, {'name': 'やまとん先生', 'url': 'http://twitter.com/search?q=%E3%82%84%E3%81%BE%E3%81%A8%E3%82%93%E5%85%88%E7%94%9F', 'promoted_content': None, 'query': '%E3%82%84%E3%81%BE%E3%81%A8%E3%82%93%E5%85%88%E7%94%9F', 'tweet_volume': None}, {'name': 'Zendaya', 'url': 'http://twitter.com/search?q=Zendaya', 'promoted_content': None, 'query': 'Zendaya', 'tweet_volume': 158640}, {'name': 'Maddie', 'url': 'http://twitter.com/search?q=Maddie', 'promoted_content': None, 'query': 'Maddie', 'tweet_volume': 38518}, {'name': 'Ashtray', 'url': 'http://twitter.com/search?q=Ashtray', 'promoted_content': None, 'query': 'Ashtray', 'tweet_volume': None}, {'name': 'Tansu Çiller', 'url': 'http://twitter.com/search?q=%22Tansu+%C3%87iller%22', 'promoted_content': None, 'query': '%22Tansu+%C3%87iller%22', 'tweet_volume': None}, {'name': '立憲・末松義規議員', 'url': 'http://twitter.com/search?q=%E7%AB%8B%E6%86%B2%E3%83%BB%E6%9C%AB%E6%9D%BE%E7%BE%A9%E8%A6%8F%E8%AD%B0%E5%93%A1', 'promoted_content': None, 'query': '%E7%AB%8B%E6%86%B2%E3%83%BB%E6%9C%AB%E6%9D%BE%E7%BE%A9%E8%A6%8F%E8%AD%B0%E5%93%A1', 'tweet_volume': None}, {'name': 'ランファ', 'url': 'http://twitter.com/search?q=%E3%83%A9%E3%83%B3%E3%83%95%E3%82%A1', 'promoted_content': None, 'query': '%E3%83%A9%E3%83%B3%E3%83%95%E3%82%A1', 'tweet_volume': 31601}, {'name': '뉴이스트', 'url': 'http://twitter.com/search?q=%EB%89%B4%EC%9D%B4%EC%8A%A4%ED%8A%B8', 'promoted_content': None, 'query': '%EB%89%B4%EC%9D%B4%EC%8A%A4%ED%8A%B8', 'tweet_volume': 17313}, {'name': 'Tiziano Ferro', 'url': 'http://twitter.com/search?q=%22Tiziano+Ferro%22', 'promoted_content': None, 'query': '%22Tiziano+Ferro%22', 'tweet_volume': None}, {'name': 'ファイナルミキサー', 'url': 'http://twitter.com/search?q=%E3%83%95%E3%82%A1%E3%82%A4%E3%83%8A%E3%83%AB%E3%83%9F%E3%82%AD%E3%82%B5%E3%83%BC', 'promoted_content': None, 'query': '%E3%83%95%E3%82%A1%E3%82%A4%E3%83%8A%E3%83%AB%E3%83%9F%E3%82%AD%E3%82%B5%E3%83%BC', 'tweet_volume': None}, {'name': 'jisoo', 'url': 'http://twitter.com/search?q=jisoo', 'promoted_content': None, 'query': 'jisoo', 'tweet_volume': 340519}, {'name': 'Lina', 'url': 'http://twitter.com/search?q=Lina', 'promoted_content': None, 'query': 'Lina', 'tweet_volume': 107987}, {'name': 'Pledis', 'url': 'http://twitter.com/search?q=Pledis', 'promoted_content': None, 'query': 'Pledis', 'tweet_volume': 108854}, {'name': 'dominic fike', 'url': 'http://twitter.com/search?q=%22dominic+fike%22', 'promoted_content': None, 'query': '%22dominic+fike%22', 'tweet_volume': 15835}, {'name': 'ロシア大幅利上げ', 'url': 'http://twitter.com/search?q=%E3%83%AD%E3%82%B7%E3%82%A2%E5%A4%A7%E5%B9%85%E5%88%A9%E4%B8%8A%E3%81%92', 'promoted_content': None, 'query': '%E3%83%AD%E3%82%B7%E3%82%A2%E5%A4%A7%E5%B9%85%E5%88%A9%E4%B8%8A%E3%81%92', 'tweet_volume': None}, {'name': '異例の声明', 'url': 'http://twitter.com/search?q=%E7%95%B0%E4%BE%8B%E3%81%AE%E5%A3%B0%E6%98%8E', 'promoted_content': None, 'query': '%E7%95%B0%E4%BE%8B%E3%81%AE%E5%A3%B0%E6%98%8E', 'tweet_volume': None}, {'name': '日本の追加制裁', 'url': 'http://twitter.com/search?q=%E6%97%A5%E6%9C%AC%E3%81%AE%E8%BF%BD%E5%8A%A0%E5%88%B6%E8%A3%81', 'promoted_content': None, 'query': '%E6%97%A5%E6%9C%AC%E3%81%AE%E8%BF%BD%E5%8A%A0%E5%88%B6%E8%A3%81', 'tweet_volume': None}, {'name': 'minhyun', 'url': 'http://twitter.com/search?q=minhyun', 'promoted_content': None, 'query': 'minhyun', 'tweet_volume': None}, {'name': '通貨防衛', 'url': 'http://twitter.com/search?q=%E9%80%9A%E8%B2%A8%E9%98%B2%E8%A1%9B', 'promoted_content': None, 'query': '%E9%80%9A%E8%B2%A8%E9%98%B2%E8%A1%9B', 'tweet_volume': None}, {'name': '米ホワイトハウス', 'url': 'http://twitter.com/search?q=%E7%B1%B3%E3%83%9B%E3%83%AF%E3%82%A4%E3%83%88%E3%83%8F%E3%82%A6%E3%82%B9', 'promoted_content': None, 'query': '%E7%B1%B3%E3%83%9B%E3%83%AF%E3%82%A4%E3%83%88%E3%83%8F%E3%82%A6%E3%82%B9', 'tweet_volume': None}, {'name': 'ルーブル', 'url': 'http://twitter.com/search?q=%E3%83%AB%E3%83%BC%E3%83%96%E3%83%AB', 'promoted_content': None, 'query': '%E3%83%AB%E3%83%BC%E3%83%96%E3%83%AB', 'tweet_volume': 29897}, {'name': 'Laurie', 'url': 'http://twitter.com/search?q=Laurie', 'promoted_content': None, 'query': 'Laurie', 'tweet_volume': 45052}, {'name': 'Sadi Somuncuoğlu', 'url': 'http://twitter.com/search?q=%22Sadi+Somuncuo%C4%9Flu%22', 'promoted_content': None, 'query': '%22Sadi+Somuncuo%C4%9Flu%22', 'tweet_volume': None}, {'name': 'Wochenstart', 'url': 'http://twitter.com/search?q=Wochenstart', 'promoted_content': None, 'query': 'Wochenstart', 'tweet_volume': None}, {'name': 'HANGGANG SA MULI ALEIAN', 'url': 'http://twitter.com/search?q=%22HANGGANG+SA+MULI+ALEIAN%22', 'promoted_content': None, 'query': '%22HANGGANG+SA+MULI+ALEIAN%22', 'tweet_volume': 18804}, {'name': '中田翔選手', 'url': 'http://twitter.com/search?q=%E4%B8%AD%E7%94%B0%E7%BF%94%E9%81%B8%E6%89%8B', 'promoted_content': None, 'query': '%E4%B8%AD%E7%94%B0%E7%BF%94%E9%81%B8%E6%89%8B', 'tweet_volume': None}, {'name': 'ロシア中銀', 'url': 'http://twitter.com/search?q=%E3%83%AD%E3%82%B7%E3%82%A2%E4%B8%AD%E9%8A%80', 'promoted_content': None, 'query': '%E3%83%AD%E3%82%B7%E3%82%A2%E4%B8%AD%E9%8A%80', 'tweet_volume': None}, {'name': 'BENJI KUMUSERYE EP3', 'url': 'http://twitter.com/search?q=%22BENJI+KUMUSERYE+EP3%22', 'promoted_content': None, 'query': '%22BENJI+KUMUSERYE+EP3%22', 'tweet_volume': None}, {'name': 'Viny', 'url': 'http://twitter.com/search?q=Viny', 'promoted_content': None, 'query': 'Viny', 'tweet_volume': 25361}, {'name': 'Baekho', 'url': 'http://twitter.com/search?q=Baekho', 'promoted_content': None, 'query': 'Baekho', 'tweet_volume': 12652}]

## Data Cleaning

In [89]:
for index, row in df.iterrows():
    df.at[index,'reference_id'] = row["asset_contract_address"] + "-" + str(row["nft_id"])

# df['traits_string'] = df['traits_string'].str.replace(';',' ') # this needs to be changed in BAYC dataset to ;;

df.head()

,nft_id,name,asset_description,asset_contract_address,collection_name,collection_description,collection_slug,collection_verification,creator_username,creator_address,...,traits_string,total_rarity,num_sales,last_sale_timestamp,last_sale_total_price,last_sale_from_account_address,top_bid,open_sea_link,image_url,reference_id
0,2541585283815458503018281017495372409420154545...,CelebCard #84 Snoop Dogg,NaN,0x495f947276749ce646f68ac8c248420045cb7b5e,Mesmerizer,No theme. No traits. No rules. A treasure trov...,mesmerizer,False,NaN,0x3830dce8b8f5543404e005776b4de22870c01d64,...,NaN,0.0,0,NaN,NaN,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/DwknciiKsguS...,0x495f947276749ce646f68ac8c248420045cb7b5e-254...
1,4460258260744616717349398633449740654585409544...,3D Penguin Planet Official Collection,3D Penguin Planet Collection It was hand paint...,0x495f947276749ce646f68ac8c248420045cb7b5e,3D Penguin Planet Official Collection,3D Penguin Planet Official Collection It was h...,3d-penguin-planet-official-collection,False,NaN,0x629c2ac970da51a3fa29af4015e06c250c267e36,...,NaN,0.0,0,NaN,NaN,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/yzniUTh85SYY...,0x495f947276749ce646f68ac8c248420045cb7b5e-446...
2,1143238369460653929904223751867794581426030911...,VECTOR KAS 10 (The Relax),VECTOR KAS 10,0x495f947276749ce646f68ac8c248420045cb7b5e,Kalvintaka Collection,NaN,kalvintaka-collection,False,Creative_FineArts_and_Designs,0xfcc0ffa7b48f9af939ed6e9d3c535e371ab2f17f,...,NaN,0.0,0,NaN,NaN,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/2xDLW3Nrrt8u...,0x495f947276749ce646f68ac8c248420045cb7b5e-114...
3,5742295951199733757787373026863398866922647154...,Gooniez #1989,"A gang of 8,888 gooniez unleashed to wreak hav...",0x495f947276749ce646f68ac8c248420045cb7b5e,Metaverse GooniezNFT,"A gang of 8,888 gooniez unleashed to wreak hav...",metaverse-goonieznft,False,GooniezNFTCollection,0x7ef43e4a20315830feacb23fe17f7cf2d49f2491,...,NaN,0.0,0,NaN,NaN,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/Y4lDr3FzA7xm...,0x495f947276749ce646f68ac8c248420045cb7b5e-574...
4,1006254684714400059060824656421626037946389019...,Darumaa Soul Story.#3,Works that are created by an Extraterrestrial ...,0x495f947276749ce646f68ac8c248420045cb7b5e,Extraterrestrial Soul Darumaa,Darumaa. Not Real & Reality.\n\nWorks that are...,darumaa,False,FRABATO,0xde77ff31b3601243b0f41441e1f015456b2b1ad2,...,NaN,0.0,0,NaN,NaN,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/9xcm5vesaQYE...,0x495f947276749ce646f68ac8c248420045cb7b5e-100...

Clean duplicate data in dataframe

*This needs to be saved as well*

In [90]:
# df.shape[0]

# dropping ALL duplicate values
# df.drop_duplicates(subset ="reference_id", keep = False, inplace = True)

# dropping ALL duplicate values
df.drop_duplicates(subset="reference_id", keep='first', inplace = True)

df.shape[0]

3872

save updated df in csv

In [91]:
# import os
# updated_assets_file_path = "/content/drive/MyDrive/Datasets/FYP/collected-nft-assets-unique"

# save updated dataframe to csv & save csv to Google Drive
# df.to_csv(updated_assets_file_path, mode='a', sep='\t', index=False, header=(not os.path.exists(updated_assets_file_path)), encoding='utf-8')

In [92]:
df.iloc[0]

nft_id                            2541585283815458503018281017495372409420154545...
name                                                       CelebCard #84 Snoop Dogg
asset_description                                                               NaN
asset_contract_address                   0x495f947276749ce646f68ac8c248420045cb7b5e
collection_name                                                          Mesmerizer
collection_description            No theme. No traits. No rules. A treasure trov...
collection_slug                                                          mesmerizer
collection_verification                                                       False
creator_username                                                                NaN
creator_address                          0x3830dce8b8f5543404e005776b4de22870c01d64
creator_profile_img_url           https://storage.googleapis.com/opensea-static/...
owner_username                                                          NullAddress
owner_address                            0x0000000000000000000000000000000000000000
owner_profile_img_url             https://storage.googleapis.com/opensea-static/...
traits_string                                                                   NaN
total_rarity                                                                    0.0
num_sales                                                                         0
last_sale_timestamp                                                             NaN
last_sale_total_price                                                           NaN
last_sale_from_account_address                                                  NaN
top_bid                                                                         NaN
open_sea_link                     https://opensea.io/assets/0x495f947276749ce646...
image_url                         https://lh3.googleusercontent.com/DwknciiKsguS...
reference_id                      0x495f947276749ce646f68ac8c248420045cb7b5e-254...
Name: 0, dtype: object

## Rake Vectorizer
Vectorize words

In [93]:
def vectorize_and_extract_key_words_in_column( column_name ):

  # initializing the new column
  new_column_name = 'Key_words_' + column_name
  df[new_column_name] = ""

  for index, row in df.iterrows():
      column_cell = row[column_name]

      
      # check if the cell has a string, to apply NLP
      if isinstance(column_cell, str):
        # instantiating Rake, by default it uses english stopwords from NLTK
        # and discards all puntuation characters as well
        r = Rake()

        # extracting the words by passing the text
        r.extract_keywords_from_text(column_cell)

        # getting the dictionary with key words as keys and their scores as values
        key_words_dict_scores = r.get_word_degrees()

        # print(key_words_dict_scores.keys())

        # assigning the key words to the new column for the corresponding NFT
        # row[new_column_name] = list(key_words_dict_scores.keys()) # this doesn't work for some reason

        df.at[index, new_column_name]=list(key_words_dict_scores.keys())

      else:
        df.at[index, new_column_name] = None

  # dropping the column_name column
  df.drop(columns = [column_name], inplace = True)

In [94]:
vectorize_and_extract_key_words_in_column('name')
vectorize_and_extract_key_words_in_column('asset_description')
vectorize_and_extract_key_words_in_column('collection_name')
vectorize_and_extract_key_words_in_column('collection_description')

df.head()

,nft_id,asset_contract_address,collection_slug,collection_verification,creator_username,creator_address,creator_profile_img_url,owner_username,owner_address,owner_profile_img_url,...,last_sale_total_price,last_sale_from_account_address,top_bid,open_sea_link,image_url,reference_id,Key_words_name,Key_words_asset_description,Key_words_collection_name,Key_words_collection_description
0,2541585283815458503018281017495372409420154545...,0x495f947276749ce646f68ac8c248420045cb7b5e,mesmerizer,False,NaN,0x3830dce8b8f5543404e005776b4de22870c01d64,https://storage.googleapis.com/opensea-static/...,NullAddress,0x0000000000000000000000000000000000000000,https://storage.googleapis.com/opensea-static/...,...,NaN,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/DwknciiKsguS...,0x495f947276749ce646f68ac8c248420045cb7b5e-254...,"[celebcard, 84, snoop, dogg]",None,[mesmerizer],"[theme, traits, rules, treasure, trove, pure, ..."
1,4460258260744616717349398633449740654585409544...,0x495f947276749ce646f68ac8c248420045cb7b5e,3d-penguin-planet-official-collection,False,NaN,0x629c2ac970da51a3fa29af4015e06c250c267e36,https://storage.googleapis.com/opensea-static/...,NullAddress,0x0000000000000000000000000000000000000000,https://storage.googleapis.com/opensea-static/...,...,NaN,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/yzniUTh85SYY...,0x495f947276749ce646f68ac8c248420045cb7b5e-446...,"[3d, penguin, planet, official, collection]","[3d, penguin, planet, collection, hand, painte...","[3d, penguin, planet, official, collection]","[3d, penguin, planet, official, collection, ha..."
2,1143238369460653929904223751867794581426030911...,0x495f947276749ce646f68ac8c248420045cb7b5e,kalvintaka-collection,False,Creative_FineArts_and_Designs,0xfcc0ffa7b48f9af939ed6e9d3c535e371ab2f17f,https://storage.googleapis.com/opensea-static/...,NullAddress,0x0000000000000000000000000000000000000000,https://storage.googleapis.com/opensea-static/...,...,NaN,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/2xDLW3Nrrt8u...,0x495f947276749ce646f68ac8c248420045cb7b5e-114...,"[vector, kas, 10, relax]","[vector, kas, 10]","[kalvintaka, collection]",None
3,5742295951199733757787373026863398866922647154...,0x495f947276749ce646f68ac8c248420045cb7b5e,metaverse-goonieznft,False,GooniezNFTCollection,0x7ef43e4a20315830feacb23fe17f7cf2d49f2491,https://storage.googleapis.com/opensea-static/...,NullAddress,0x0000000000000000000000000000000000000000,https://storage.googleapis.com/opensea-static/...,...,NaN,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/Y4lDr3FzA7xm...,0x495f947276749ce646f68ac8c248420045cb7b5e-574...,"[gooniez, 1989]","[gang, 8, 888, gooniez, unleashed, wreak, havo...","[metaverse, goonieznft]","[gang, 8, 888, gooniez, unleashed, wreak, havo..."
4,1006254684714400059060824656421626037946389019...,0x495f947276749ce646f68ac8c248420045cb7b5e,darumaa,False,FRABATO,0xde77ff31b3601243b0f41441e1f015456b2b1ad2,https://storage.googleapis.com/opensea-static/...,NullAddress,0x0000000000000000000000000000000000000000,https://storage.googleapis.com/opensea-static/...,...,NaN,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/9xcm5vesaQYE...,0x495f947276749ce646f68ac8c248420045cb7b5e-100...,"[darumaa, soul, story, .#, 3]","[works, created, extraterrestrial, soul, named...","[extraterrestrial, soul, darumaa]","[darumaa, real, reality, works, created, extra..."

### Combine all key words into one column

This may come handy when comparing with trends data.

In [95]:
columns = df.columns
df['All_key_words_list'] = pd.NA
df['All_key_words_str'] = ''

for index, row in df.iterrows():
  words = []
  key_words_str=''

  for col in columns:
    if col.startswith("Key_words") and row[col] != None:
      words += row[col]
      key_words_str += ' '.join(row[col])+ ' '

  # row['All_key_words_list'] = words
  # row['All_key_words_str'] = key_words_str
  df.at[index, 'All_key_words_list'] = words
  df.at[index, 'All_key_words_str'] = key_words_str

df.head()

,nft_id,asset_contract_address,collection_slug,collection_verification,creator_username,creator_address,creator_profile_img_url,owner_username,owner_address,owner_profile_img_url,...,top_bid,open_sea_link,image_url,reference_id,Key_words_name,Key_words_asset_description,Key_words_collection_name,Key_words_collection_description,All_key_words_list,All_key_words_str
0,2541585283815458503018281017495372409420154545...,0x495f947276749ce646f68ac8c248420045cb7b5e,mesmerizer,False,NaN,0x3830dce8b8f5543404e005776b4de22870c01d64,https://storage.googleapis.com/opensea-static/...,NullAddress,0x0000000000000000000000000000000000000000,https://storage.googleapis.com/opensea-static/...,...,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/DwknciiKsguS...,0x495f947276749ce646f68ac8c248420045cb7b5e-254...,"[celebcard, 84, snoop, dogg]",None,[mesmerizer],"[theme, traits, rules, treasure, trove, pure, ...","[celebcard, 84, snoop, dogg, mesmerizer, theme...",celebcard 84 snoop dogg mesmerizer theme trait...
1,4460258260744616717349398633449740654585409544...,0x495f947276749ce646f68ac8c248420045cb7b5e,3d-penguin-planet-official-collection,False,NaN,0x629c2ac970da51a3fa29af4015e06c250c267e36,https://storage.googleapis.com/opensea-static/...,NullAddress,0x0000000000000000000000000000000000000000,https://storage.googleapis.com/opensea-static/...,...,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/yzniUTh85SYY...,0x495f947276749ce646f68ac8c248420045cb7b5e-446...,"[3d, penguin, planet, official, collection]","[3d, penguin, planet, collection, hand, painte...","[3d, penguin, planet, official, collection]","[3d, penguin, planet, official, collection, ha...","[3d, penguin, planet, official, collection, 3d...",3d penguin planet official collection 3d pengu...
2,1143238369460653929904223751867794581426030911...,0x495f947276749ce646f68ac8c248420045cb7b5e,kalvintaka-collection,False,Creative_FineArts_and_Designs,0xfcc0ffa7b48f9af939ed6e9d3c535e371ab2f17f,https://storage.googleapis.com/opensea-static/...,NullAddress,0x0000000000000000000000000000000000000000,https://storage.googleapis.com/opensea-static/...,...,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/2xDLW3Nrrt8u...,0x495f947276749ce646f68ac8c248420045cb7b5e-114...,"[vector, kas, 10, relax]","[vector, kas, 10]","[kalvintaka, collection]",None,"[vector, kas, 10, relax, vector, kas, 10, kalv...",vector kas 10 relax vector kas 10 kalvintaka c...
3,5742295951199733757787373026863398866922647154...,0x495f947276749ce646f68ac8c248420045cb7b5e,metaverse-goonieznft,False,GooniezNFTCollection,0x7ef43e4a20315830feacb23fe17f7cf2d49f2491,https://storage.googleapis.com/opensea-static/...,NullAddress,0x0000000000000000000000000000000000000000,https://storage.googleapis.com/opensea-static/...,...,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/Y4lDr3FzA7xm...,0x495f947276749ce646f68ac8c248420045cb7b5e-574...,"[gooniez, 1989]","[gang, 8, 888, gooniez, unleashed, wreak, havo...","[metaverse, goonieznft]","[gang, 8, 888, gooniez, unleashed, wreak, havo...","[gooniez, 1989, gang, 8, 888, gooniez, unleash...",gooniez 1989 gang 8 888 gooniez unleashed wrea...
4,1006254684714400059060824656421626037946389019...,0x495f947276749ce646f68ac8c248420045cb7b5e,darumaa,False,FRABATO,0xde77ff31b3601243b0f41441e1f015456b2b1ad2,https://storage.googleapis.com/opensea-static/...,NullAddress,0x0000000000000000000000000000000000000000,https://storage.googleapis.com/opensea-static/...,...,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/9xcm5vesaQYE...,0x495f947276749ce646f68ac8c248420045cb7b5e-100...,"[darumaa, soul, story, .#, 3]","[works, created, extraterrestrial, soul, named...","[extraterrestrial, soul, darumaa]","[darumaa, real, reality, works, created, extra...","[darumaa, soul, story, .#, 3, works, created, ...",darumaa soul story .# 3 works created extrater...

Create `bag_of_words`

Drop useless columns

In [96]:
df['All_key_words_str'].count()

3872

In [97]:
df.set_index('reference_id', inplace = True)   # set reference_id as the index of the dataframe
df.head()

,nft_id,asset_contract_address,collection_slug,collection_verification,creator_username,creator_address,creator_profile_img_url,owner_username,owner_address,owner_profile_img_url,...,last_sale_from_account_address,top_bid,open_sea_link,image_url,Key_words_name,Key_words_asset_description,Key_words_collection_name,Key_words_collection_description,All_key_words_list,All_key_words_str
reference_id,,,,,,,,,,,,,,,,,,,,,
0x495f947276749ce646f68ac8c248420045cb7b5e-25415852838154585030182810174953724094201545459452816665085826154914734145537,2541585283815458503018281017495372409420154545...,0x495f947276749ce646f68ac8c248420045cb7b5e,mesmerizer,False,NaN,0x3830dce8b8f5543404e005776b4de22870c01d64,https://storage.googleapis.com/opensea-static/...,NullAddress,0x0000000000000000000000000000000000000000,https://storage.googleapis.com/opensea-static/...,...,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/DwknciiKsguS...,"[celebcard, 84, snoop, dogg]",None,[mesmerizer],"[theme, traits, rules, treasure, trove, pure, ...","[celebcard, 84, snoop, dogg, mesmerizer, theme...",celebcard 84 snoop dogg mesmerizer theme trait...
0x495f947276749ce646f68ac8c248420045cb7b5e-44602582607446167173493986334497406545854095441469804519114872108262954631169,4460258260744616717349398633449740654585409544...,0x495f947276749ce646f68ac8c248420045cb7b5e,3d-penguin-planet-official-collection,False,NaN,0x629c2ac970da51a3fa29af4015e06c250c267e36,https://storage.googleapis.com/opensea-static/...,NullAddress,0x0000000000000000000000000000000000000000,https://storage.googleapis.com/opensea-static/...,...,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/yzniUTh85SYY...,"[3d, penguin, planet, official, collection]","[3d, penguin, planet, collection, hand, painte...","[3d, penguin, planet, official, collection]","[3d, penguin, planet, official, collection, ha...","[3d, penguin, planet, official, collection, 3d...",3d penguin planet official collection 3d pengu...
0x495f947276749ce646f68ac8c248420045cb7b5e-114323836946065392990422375186779458142603091121322655546213463221980662595585,1143238369460653929904223751867794581426030911...,0x495f947276749ce646f68ac8c248420045cb7b5e,kalvintaka-collection,False,Creative_FineArts_and_Designs,0xfcc0ffa7b48f9af939ed6e9d3c535e371ab2f17f,https://storage.googleapis.com/opensea-static/...,NullAddress,0x0000000000000000000000000000000000000000,https://storage.googleapis.com/opensea-static/...,...,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/2xDLW3Nrrt8u...,"[vector, kas, 10, relax]","[vector, kas, 10]","[kalvintaka, collection]",None,"[vector, kas, 10, relax, vector, kas, 10, kalv...",vector kas 10 relax vector kas 10 kalvintaka c...
0x495f947276749ce646f68ac8c248420045cb7b5e-57422959511997337577873730268633988669226471548944456734432444570123223695361,5742295951199733757787373026863398866922647154...,0x495f947276749ce646f68ac8c248420045cb7b5e,metaverse-goonieznft,False,GooniezNFTCollection,0x7ef43e4a20315830feacb23fe17f7cf2d49f2491,https://storage.googleapis.com/opensea-static/...,NullAddress,0x0000000000000000000000000000000000000000,https://storage.googleapis.com/opensea-static/...,...,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/Y4lDr3FzA7xm...,"[gooniez, 1989]","[gang, 8, 888, gooniez, unleashed, wreak, havo...","[metaverse, goonieznft]","[gang, 8, 888, gooniez, unleashed, wreak, havo...","[gooniez, 1989, gang, 8, 888, gooniez, unleash...",gooniez 1989 gang 8 888 gooniez unleashed wrea...
0x495f947276749ce646f68ac8c248420045cb7b5e-100625468471440005906082465642162603794638901987049655284968819362997051850753,1006254684714400059060824656421626037946389019...,0x495f947276749ce646f68ac8c248420045cb7b5e,darumaa,False,FRABATO,0xde77ff31b3601243b0f41441e1f015456b2b1ad2,https://storage.googleapis.com/opensea-static/...,NullAddress,0x0000000000000000000000000000000000000000,https://storage.googleapis.com/opensea-static/...,...,NaN,NaN,https://opensea.io/assets/0x495f947276749ce646...,https://lh3.googleusercontent.com/9xcm5vesaQYE...,"[darumaa, soul, story, .#, 3]","[works, created, extraterrestrial, soul, named...","[extraterrestrial, soul, darumaa]","[darumaa, real, reality, works, created, extra...","[darumaa, soul, story, .#, 3, works, created, ...",darumaa soul story .# 3 works created extrater...

In [98]:
df.drop(columns = [col for col in df.columns if not col.startswith("All_key_words")], inplace = True)
df.head()

,All_key_words_list,All_key_words_str
reference_id,,
0x495f947276749ce646f68ac8c248420045cb7b5e-25415852838154585030182810174953724094201545459452816665085826154914734145537,"[celebcard, 84, snoop, dogg, mesmerizer, theme...",celebcard 84 snoop dogg mesmerizer theme trait...
0x495f947276749ce646f68ac8c248420045cb7b5e-44602582607446167173493986334497406545854095441469804519114872108262954631169,"[3d, penguin, planet, official, collection, 3d...",3d penguin planet official collection 3d pengu...
0x495f947276749ce646f68ac8c248420045cb7b5e-114323836946065392990422375186779458142603091121322655546213463221980662595585,"[vector, kas, 10, relax, vector, kas, 10, kalv...",vector kas 10 relax vector kas 10 kalvintaka c...
0x495f947276749ce646f68ac8c248420045cb7b5e-57422959511997337577873730268633988669226471548944456734432444570123223695361,"[gooniez, 1989, gang, 8, 888, gooniez, unleash...",gooniez 1989 gang 8 888 gooniez unleashed wrea...
0x495f947276749ce646f68ac8c248420045cb7b5e-100625468471440005906082465642162603794638901987049655284968819362997051850753,"[darumaa, soul, story, .#, 3, works, created, ...",darumaa soul story .# 3 works created extrater...

## Modeling

### Generic Content based matches between items

In order to detect similarities between NFT content, I need to vectorize, as I mentioned above. I decided to use CountVectorizer rather than TfIdfVectorizer for one simple reason: I need a simple frequency counter for each word in my bag_of_words column. Tf-Idf tends to give less importance to the words that are more present in the entire corpus (our whole column, in this case) which is not what we want for this application, because every word is important to detect similarity! 

*It seems like Tf-Idf would give more meaningful results* for ranking - check this later. For relevance, CountVectorizer seems to be ok.

Once I have the matrix containing the count for each word, we can apply the cosine_similarity function

In [99]:
# instantiating and generating the count matrix
count = CountVectorizer()   # used to transform a given text into a vector on the basis of the frequency (count) of each word that occurs in the entire text
count_matrix = count.fit_transform(df['All_key_words_str'])

# print(count_matrix)
count_matrix.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [100]:
count_matrix.shape

(3872, 7527)

in the count_matrix, i seems to be the NFT, j seems to be each word in the bag_of_words per NFT. the value at i, j gives the frequency of each word in the entire column of bag_of_words.

For some reason (need to find out) this frequency is needed to calculate the cosine similarity between the content in NFTs. - *The definition of similarity between two vectors u and v is, in fact, the ratio between their dot product and the product of their magnitudes.*

In [101]:
# creating a Series for the NFT reference_id so they are associated to an ordered numerical
# list I will use later to match the indexes - easy to refer the NFT reference_id by index from the array that is created (cosine_sim)
indices = pd.Series(df.index)
indices[:5]

0    0x495f947276749ce646f68ac8c248420045cb7b5e-254...
1    0x495f947276749ce646f68ac8c248420045cb7b5e-446...
2    0x495f947276749ce646f68ac8c248420045cb7b5e-114...
3    0x495f947276749ce646f68ac8c248420045cb7b5e-574...
4    0x495f947276749ce646f68ac8c248420045cb7b5e-100...
Name: reference_id, dtype: object

Check if this concern can be addressed: Having cosine_sim in-memory can be a memory constraint for larger datasets

In [102]:
# generating the cosine similarity matrix
cosine_sim = cosine_similarity(count_matrix, count_matrix)

In [103]:
# function that takes in NFT reference_id (nft_contract_address-nft_id) as input and returns the top 10 recommended NFTs
def content_based_recommendations(reference_id, cosine_sim = cosine_sim):
    
    recommended_NFTs = []
    
    # getting the index of the NFT that matches the reference_id
    idx = indices[indices == reference_id].index[0]

    # creating a Series with the similarity scores in descending order
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)

    # getting the indexes of the 10 most similar NFTs
    top_10_indexes = list(score_series.iloc[1:11].index)
    
    # populating the list with the reference_ids of the best 10 matching NFT
    for i in top_10_indexes:
        recommended_NFTs.append(list(df.index)[i])
        
    return recommended_NFTs

### Trends based Content maching

In [104]:
# trending_phrases = ['ROMCOM SERIES FOR HAESOO', 'Golden Corral', 'Wordle 228', 'Tietê', 'BOP TRACKLIST', '伊東純也', 'JIKJIN FOCUS FILM', 'NINJAPAN 2021', '一気読み', 'ムササビ', 'オーストラリア', 'WONPIL Concept Photo 3', 'Benzine 39', 'あーりん', 'البليهي', 'Kraft', '花枝ちゃん', 'HAPPY BIRTHDAY GEONU', 'ちゃん誕生日', 'サウジアラビア', '도영듀스', '凛ちゃん', 'SECRETCRUSH TRAILER', 'Best Entertainer Jungkook', 'UM CORPO DE VERÃO', 'Quito', 'Damn Brady', 'Schefter', '日村さん', 'SMILE FOR MEW', 'HBCUs', 'もやとらっしー', 'Lucas', '拷問部屋', 'Wordle 244 X', '視聴覚室', '子供部屋', 'Gustavo', '警視庁初摘発', '日本人の覚醒剤製造', '暴力団幹部とYouTuber組員ら逮捕', 'Donda 2', 'Tiago', 'ベランダ', 'Peaky Peaky', '당신 이야기', '대신 전해', '¥930,000', 'RED VELVET MARCH COMEBACK', 'Embiid', 'Jack Harlow', 'sabrina', 'Nonku', 'Giannis', '国民負担率', '¥115,000', '鬱アニメ', "GUESS WHO'S BACK", 'TBS NEWS', '¥139,000', 'sungas', '超大作怪獣映画', 'Middleton', '男性医師の有罪判決', 'Barão da Piscadinha', '自爆デッキ', 'Stem Player', 'はしもっちゃん', 'Aグループ', 'Eslo', 'あやかし譚', 'おててまもる君', 'ミラキュラス', 'Yeat']
# phrases contains all trending words

In [105]:
import pprint   # well-formatted print output

pp = pprint.PrettyPrinter(indent=1)

**TODO EXTRA (not that important): Fetch each group of trends at a time from MongoDB/ get min_tweet_volume of only trends fetched at the same `created_datetime`**

In [106]:
# Connect to MongoDB
import pymongo

mongo_client = pymongo.MongoClient("mongodb+srv://admin:2KRv1funPDgawFu7@recsyscluster.lvxb6.mongodb.net")
mydb = mongo_client["nft-recsys"]
trends_collection = mydb["trends"]

In [107]:
twitter_trends = []

for x in trends_collection.find():
  # pp.pprint(x)
  twitter_trends.append(x)

len(twitter_trends)

677

*rethink if there's a benefit before attempting:* Preprocess batch-wise (based on created_timestamp of the trend)

to avoid majority of the data getting the same score

In [108]:
pre_processed_twitter_trends = []

bag_of_trends_phrases = []
min_tweet_volume = None

for trend in twitter_trends:
  if trend['name'] not in bag_of_trends_phrases :
    # ignore duplicates (twitter API bug? sometimes trends are duplicated) 
    bag_of_trends_phrases.append(trend['name'])

    pre_processed_trend = trend

    #  remove hashtags
    if trend['name'][0:1] == '#':
      # remove hashtag
      pre_processed_trend['name'] = trend['name'][1:]


    #  TODO (Good to have): split words that are combined - usually happens for hashtags

    # update min_tweet_volume
    if trend['tweet_volume']:
      if min_tweet_volume == None:
        # first trend which has a tweet_volume
        min_tweet_volume = trend['tweet_volume']
      elif trend['tweet_volume'] < min_tweet_volume:
        # update min_tweet_volume
        min_tweet_volume = trend['tweet_volume']

    #  convert name to lower case
    pre_processed_trend['name'] = pre_processed_trend['name'].lower()

    pre_processed_twitter_trends.append(pre_processed_trend)

In [109]:
# add min tweet volume for tweets with no volume
for index, trend in enumerate(pre_processed_twitter_trends):
  if trend['tweet_volume'] == None:
      pre_processed_twitter_trends[index]['tweet_volume'] = min_tweet_volume - 1


# print(pre_processed_twitter_trends)
# pp.pprint(pre_processed_twitter_trends)

Calculate Median Tweet volume

An impact score can be calculated separately as well.

In [110]:
import statistics

# add all tweets with tweet volumes into an array
tweet_volumes_array = []
for tweet in pre_processed_twitter_trends:
  if tweet['tweet_volume'] != None:
    tweet_volumes_array.append(tweet['tweet_volume'])

print("tweet_volumes_array:", tweet_volumes_array)

# calculate median tweet volume
median_tweet_volume = statistics.median(tweet_volumes_array)
print(median_tweet_volume)

tweet_volumes_array: [93293, 42633, 39283, 23107, 100974, 10067, 10067, 10067, 10067, 25361, 89051, 31601, 17313, 1005172, 416023, 10067, 10067, 10067, 12652, 246787, 10067, 15835, 10067, 29897, 18804, 107648, 10067, 10067, 340519, 107987, 108854, 2166180, 231872, 352427, 23904, 329769, 137511, 10067, 158640, 38518, 10067, 10067, 10067, 45052, 10067, 13042, 10067, 10067, 10067, 10067, 157809, 50826, 45403, 30507, 72009, 10067, 24828, 10067, 714522, 39695, 144277, 10067, 75079, 10067, 10067, 47340, 187744, 46210, 160537, 38774, 10067, 10067, 10067, 209811, 41258, 47885, 16816, 169233, 10068, 10067, 46852, 40693, 57987, 10067, 11898, 10067, 12851, 132987, 30256, 31689, 10067, 10067, 10067, 13115, 10067, 10067, 19663, 10067, 13613, 10067, 25074, 12403, 10067, 161699, 10119, 10067, 46882, 534696, 13133, 17988, 10393, 53963, 25791, 331381, 10067, 11106, 50082, 80803, 19394, 15764, 118078, 19153, 10067, 10067, 10067, 10067, 147962, 15265, 10067, 12718, 13844, 15369, 39150, 18746, 10067, 106297, 199846, 358528, 11307, 10067, 10067, 14423, 10067, 10978, 83176, 23817, 10067, 113425, 10067, 16435, 69935, 10067, 46606, 252857, 217455, 697610, 16283, 10067, 40665, 10067, 10067, 10067, 10067, 162352, 98872, 15255, 17808, 34394, 83760, 10067, 10067, 10067, 25086, 29843, 10067, 10067, 10067, 10067, 300397, 10067, 19624, 141058, 277238, 10067, 10067, 10067, 10067, 10067, 182237, 14254, 12891, 248102, 10067, 10067, 91196, 127423, 66728, 10067, 18349, 54252, 57660, 10559, 40103, 10067, 25801, 91496, 43006, 10067, 32657, 117191, 10067, 196871, 10067, 13122, 10067, 32528, 10067, 10067, 10067, 56075, 21863, 62164, 46461, 18879, 10067, 10067, 19338, 21256, 84828, 37546, 27594, 39288, 10067, 10067, 108368, 10067, 10973, 10067, 10067, 10067, 16008, 11493, 10067, 10067, 10067, 10618, 10067, 11478, 10067, 10067, 10067, 10067, 142237, 10067, 156677, 10067, 10067, 51453, 10067, 10067, 45904, 10067, 309937, 10067, 10067, 126240, 10067, 10067, 10067, 18162, 670917, 10067, 81285, 10067, 10067, 46381, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 14469, 10067, 10067, 10067, 49157, 94300, 63753, 10067, 10067, 10067, 10067, 14657, 10067, 29628, 10067, 10067, 10067, 10067, 24726, 27856, 13984, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 90572, 10067, 1038479, 11892, 10067, 10067, 10067, 12157, 180797, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 15684, 31763, 10067, 25610, 10067, 10067, 10067, 39111, 10067, 10067, 10067, 10067, 384796, 10067, 10067, 10067, 10067, 86123, 10067, 10067, 10067, 10067, 10067, 44788, 10067, 10067, 45310, 10067, 15060, 10067, 10067, 16518, 10067, 10067, 10067, 11155, 19620, 10067, 212352, 10067, 10067, 10067, 10067, 62977, 10557, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 128002, 10067, 469925, 274098, 58791, 66635, 113332, 10067, 10067, 36088, 10067, 101443, 10067, 56292, 24495, 84738, 21850, 340675, 15042, 265693, 46164, 10067, 260569, 12532, 10067, 21275, 10067, 86775, 32612, 115516, 557865, 10067, 162420, 10067, 10067, 40341, 108300, 197383, 10067, 131076, 72356, 423335, 67272, 10067, 10067, 10067, 10067, 10067, 98245, 10067, 10067, 14678, 10067, 23310, 10067, 10067, 10067, 21865, 30607, 10067, 10067, 10348, 10067, 10067, 103813, 20514, 124404, 11950, 12908, 10067, 10067, 14765, 10067, 81188, 18528, 10067, 10067, 10067, 37417, 12560, 10067, 10067, 10067, 10067, 17929, 10067, 10067, 126165, 10067, 18184, 23851, 10067, 10067, 10067, 10067, 10067, 29174, 10067, 10067, 20841, 16919, 309581, 17557, 10067, 54782, 10067, 10067, 81701, 30561, 10067, 365349, 20598, 10067, 10067, 10067, 49612, 10067, 10067, 10067, 10067, 11251, 10067, 10067, 10067, 64889, 10067, 10067, 17933, 10067, 10067, 10067, 10067, 10067, 10067, 15898, 313693, 33904, 10067, 33680, 10067, 22084, 403429, 10067, 280874, 59829, 192502, 170018, 10067, 10067, 61258, 56399, 12170, 11764, 76256, 86523, 18510, 10067, 49049, 110017, 82256, 10067, 32192, 10067, 10067, 22220, 1025460, 10067, 66977, 10067, 10067, 609951, 10067, 1545687, 75872, 102124, 726085, 10067, 32648, 53246, 206163, 10067, 10067, 372045, 10188, 49264, 471580, 10067, 136932, 1465254, 14481, 10067, 10067, 10067, 10067, 10067, 10067, 10067, 32542, 10067, 10067, 10067, 19797, 135749, 10067, 17571, 10067, 35781, 320845, 171125, 10067, 158760, 25159, 89528, 30189, 13979, 134286, 10067, 10067, 26604, 78881, 192376, 2987205, 74534, 18344, 10067]
10067

*Date difference calculation*

ref: https://stackoverflow.com/a/151211/11005638

In [111]:
# trend_datetime = twitter_trends[-1]['created_datetime']
# print(trend_datetime)

# d0 = date(2021, 8, 18)
# d0 = trend_datetime.date()
d1 = datetime.now().date()

def get_date_diff(d0, d1):
  delta = d1 - d0
  # print(delta.days)
  return delta.days

# get_date_diff(d0, datetime.now().date())
# get_date_diff(trend_datetime.date(), datetime.now().date())

Calculate `trend_score` for each trend

In [112]:
current_date = datetime.now().date()
mu = 0.1 # constant

for trend in pre_processed_twitter_trends:
  volume = trend['tweet_volume']
  trend_impact_score = (volume/ median_tweet_volume)

  trend_datetime = trend['created_datetime']
  date_diff = get_date_diff(trend_datetime.date(), current_date)

  if 'sentiment_score' in trend:
    sentiment = trend['sentiment_score']
    trend_score = sentiment*trend_impact_score/ (mu + date_diff)
  else:
    # this will be taken as sentiment=1 which is in between neutral and positive
    trend_score = trend_impact_score/ (mu + date_diff)

  trend['trend_score'] = trend_score

Give a score for each row (NFT) based on the matching content

In [113]:
df['trend_score'] = pd.NA
df['matched_trends'] = pd.NA
# not_interested_trends = []  # defined by admin/ each user?

for index, row in df.iterrows():
  new_trend_match_score = 0
  matched_trends_to_item = []

  for trend in pre_processed_twitter_trends:

    if trend['name'] in row['All_key_words_list']:
    # if the content matches

      # calculate trend_score for each trend before trying to match because this score will be the same for all content - total score will be an aggregate
      new_trend_match_score += trend['trend_score']

      # add trend to matched_trends_to_item
      matched_trends_to_item.append(trend['name'])

      print(trend, "\n",row)

  df.at[index, 'trend_score'] = new_trend_match_score
  # save list of trends matched with item
  df.at[index, 'matched_trends'] = matched_trends_to_item

{'_id': ObjectId('622e388aee4a66d5042f869c'), 'name': 'elliot', 'url': 'http://twitter.com/search?q=Elliot', 'promoted_content': None, 'query': 'Elliot', 'tweet_volume': 231872, 'created_datetime': datetime.datetime(2022, 2, 28, 13, 0), 'woeid': 1, 'sentiment_score': 1.0777, 'trend_score': 0.5160610074661928}
 All_key_words_list    [old, paint, 128, elliot, page, mesmerizer, th...
All_key_words_str     old paint 128 elliot page mesmerizer theme tra...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-107628504515518689987342262222228454948876366026517717055271263417611411521537, dtype: object
{'_id': ObjectId('623b0f5ea7c0841e994d424f'), 'name': 'rice', 'url': 'http://twitter.com/search?q=Rice', 'promoted_content': None, 'query': 'Rice', 'tweet_volume': 64889, 'created_datetime': datetime.datetime(2022, 3, 23, 12, 15, 26), 'woeid': 44418, 'sentiment_score': -0.0841, 'trend_score': -0.021596992975747745}
 All_key_words_list    [nasi, lemak, vassal, card, spicy, rice, meal,...
All_key_words_str     nasi lemak vassal card spicy rice meal egg pea...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-82256463676502440146450897687557167086816165697899976211264002330492657467492, dtype: object
{'_id': ObjectId('625a74193d8b46e9766c7ef0'), 'name': 'africa', 'url': 'http://twitter.com/search?q=Africa', 'promoted_content': None, 'query': 'Africa', 'tweet_volume': 170018, 'created_datetime': datetime.datetime(2022, 4, 16, 7, 45, 29), 'woeid': 44418, 'sentiment_score': 0.3776, 'trend_score': 5.797411596846582}
 All_key_words_list    [amandelele, africa]
All_key_words_str       amandelele africa
trend_score                           <NA>
matched_trends                        <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-4681315841332783359872218394132880425029351767574165810619795540587963219969, dtype: object
{'_id': ObjectId('625a74193d8b46e9766c7ef0'), 'name': 'africa', 'url': 'http://twitter.com/search?q=Africa', 'promoted_content': None, 'query': 'Africa', 'tweet_volume': 170018, 'created_datetime': datetime.datetime(2022, 4, 16, 7, 45, 29), 'woeid': 44418, 'sentiment_score': 0.3776, 'trend_score': 5.797411596846582}
 All_key_words_list    [haze, monkey, society, genesis, nft, haze, mo...
All_key_words_str     haze monkey society genesis nft haze monkey so...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0xd85ebb24bc0c2fcd6901cc9ae7409e41d4a9e0a3-342, dtype: object
{'_id': ObjectId('625a74193d8b46e9766c7ef0'), 'name': 'africa', 'url': 'http://twitter.com/search?q=Africa', 'promoted_content': None, 'query': 'Africa', 'tweet_volume': 170018, 'created_datetime': datetime.datetime(2022, 4, 16, 7, 45, 29), 'woeid': 44418, 'sentiment_score': 0.3776, 'trend_score': 5.797411596846582}
 All_key_words_list    [haze, monkey, society, genesis, nft, haze, mo...
All_key_words_str     haze monkey society genesis nft haze monkey so...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0xd85ebb24bc0c2fcd6901cc9ae7409e41d4a9e0a3-341, dtype: object
{'_id': ObjectId('625a74193d8b46e9766c7efe'), 'name': 'boyfriends', 'url': 'http://twitter.com/search?q=Boyfriends', 'promoted_content': None, 'query': 'Boyfriends', 'tweet_volume': 75872, 'created_datetime': datetime.datetime(2022, 4, 16, 7, 45, 29), 'woeid': 44418, 'sentiment_score': -0.0622, 'trend_score': -0.4261663581278163}
 All_key_words_list    [到底要带谁回家过年呢, going, home, new, year, list, boy...
All_key_words_str     到底要带谁回家过年呢 going home new year list boyfriends...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-21501015388731809064841095921007249806046747253819384677393285554247835844609, dtype: object
{'_id': ObjectId('623842fd40ad6ffd9069b797'), 'name': 'karma', 'url': 'http://twitter.com/search?q=Karma', 'promoted_content': None, 'query': 'Karma', 'tweet_volume': 84738, 'created_datetime': datetime.datetime(2022, 3, 21, 9, 18, 53), 'woeid': 44418, 'sentiment_score': 0.7826, 'trend_score': 0.24307970105826018}
 All_key_words_list    [boundary, 2367, 노상현, south, korea, work, brin...
All_key_words_str     boundary 2367 노상현 south korea work bring good ...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-68800123458035658143408460056219206378254568321398204671677927734292982530049, dtype: object
{'_id': ObjectId('622e3927ee4a66d5042f86c9'), 'name': 'ronaldo', 'url': 'http://twitter.com/search?q=Ronaldo', 'promoted_content': None, 'query': 'Ronaldo', 'tweet_volume': 714522, 'created_datetime': datetime.datetime(2022, 3, 13, 14, 0), 'woeid': 1, 'sentiment_score': 1.0918, 'trend_score': 2.2077582182284674}
 All_key_words_list    [ether, art, 39, cristiano, ronaldo, mesmerize...
All_key_words_str     ether art 39 cristiano ronaldo mesmerizer them...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-94916783746142258917689322291875902080657954662840061252830161918695223328769, dtype: object
{'_id': ObjectId('622e3927ee4a66d5042f86c9'), 'name': 'ronaldo', 'url': 'http://twitter.com/search?q=Ronaldo', 'promoted_content': None, 'query': 'Ronaldo', 'tweet_volume': 714522, 'created_datetime': datetime.datetime(2022, 3, 13, 14, 0), 'woeid': 1, 'sentiment_score': 1.0918, 'trend_score': 2.2077582182284674}
 All_key_words_list    [stars, poster, 09, cristiano, ronaldo, mesmer...
All_key_words_str     stars poster 09 cristiano ronaldo mesmerizer t...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-107628504515518689987342262222228454948876366026517717055271263437402620821505, dtype: object
{'_id': ObjectId('623842fd40ad6ffd9069b797'), 'name': 'karma', 'url': 'http://twitter.com/search?q=Karma', 'promoted_content': None, 'query': 'Karma', 'tweet_volume': 84738, 'created_datetime': datetime.datetime(2022, 3, 21, 9, 18, 53), 'woeid': 44418, 'sentiment_score': 0.7826, 'trend_score': 0.24307970105826018}
 All_key_words_list    [boundary, 2370, 노상현, south, korea, work, brin...
All_key_words_str     boundary 2370 노상현 south korea work bring good ...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-68800123458035658143408460056219206378254568321398204671677927736492005785601, dtype: object
{'_id': ObjectId('623b0f5ea7c0841e994d425b'), 'name': 'beckham', 'url': 'http://twitter.com/search?q=Beckham', 'promoted_content': None, 'query': 'Beckham', 'tweet_volume': 10067, 'created_datetime': datetime.datetime(2022, 3, 23, 12, 15, 26), 'woeid': 44418, 'sentiment_score': 0.7677, 'trend_score': 0.030585657370517928}
 All_key_words_list    [oil, portrait, 100, david, beckham, mesmerize...
All_key_words_str     oil portrait 100 david beckham mesmerizer them...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-94916783746142258917689322291875902080657954662840061252830161924192781467649, dtype: object
{'_id': ObjectId('623842fd40ad6ffd9069b797'), 'name': 'karma', 'url': 'http://twitter.com/search?q=Karma', 'promoted_content': None, 'query': 'Karma', 'tweet_volume': 84738, 'created_datetime': datetime.datetime(2022, 3, 21, 9, 18, 53), 'woeid': 44418, 'sentiment_score': 0.7826, 'trend_score': 0.24307970105826018}
 All_key_words_list    [boundary, 2371, 노상현, south, korea, work, brin...
All_key_words_str     boundary 2371 노상현 south korea work bring good ...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-68800123458035658143408460056219206378254568321398204671677927737591517413377, dtype: object
{'_id': ObjectId('625a74193d8b46e9766c7ef0'), 'name': 'africa', 'url': 'http://twitter.com/search?q=Africa', 'promoted_content': None, 'query': 'Africa', 'tweet_volume': 170018, 'created_datetime': datetime.datetime(2022, 4, 16, 7, 45, 29), 'woeid': 44418, 'sentiment_score': 0.3776, 'trend_score': 5.797411596846582}
 All_key_words_list    [haze, monkey, society, genesis, nft, haze, mo...
All_key_words_str     haze monkey society genesis nft haze monkey so...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0xd85ebb24bc0c2fcd6901cc9ae7409e41d4a9e0a3-346, dtype: object
{'_id': ObjectId('625a74193d8b46e9766c7ef0'), 'name': 'africa', 'url': 'http://twitter.com/search?q=Africa', 'promoted_content': None, 'query': 'Africa', 'tweet_volume': 170018, 'created_datetime': datetime.datetime(2022, 4, 16, 7, 45, 29), 'woeid': 44418, 'sentiment_score': 0.3776, 'trend_score': 5.797411596846582}
 All_key_words_list    [haze, monkey, society, genesis, nft, haze, mo...
All_key_words_str     haze monkey society genesis nft haze monkey so...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0xd85ebb24bc0c2fcd6901cc9ae7409e41d4a9e0a3-345, dtype: object
{'_id': ObjectId('623842fd40ad6ffd9069b797'), 'name': 'karma', 'url': 'http://twitter.com/search?q=Karma', 'promoted_content': None, 'query': 'Karma', 'tweet_volume': 84738, 'created_datetime': datetime.datetime(2022, 3, 21, 9, 18, 53), 'woeid': 44418, 'sentiment_score': 0.7826, 'trend_score': 0.24307970105826018}
 All_key_words_list    [boundary, 2372, 노상현, south, korea, work, brin...
All_key_words_str     boundary 2372 노상현 south korea work bring good ...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-68800123458035658143408460056219206378254568321398204671677927738691029041153, dtype: object
{'_id': ObjectId('623842fd40ad6ffd9069b779'), 'name': 'forest', 'url': 'http://twitter.com/search?q=Forest', 'promoted_content': None, 'query': 'Forest', 'tweet_volume': 115516, 'created_datetime': datetime.datetime(2022, 3, 21, 9, 18, 53), 'woeid': 44418, 'sentiment_score': 1.1187, 'trend_score': 0.4736814970692669}
 All_key_words_list    [1863, detective, renard, famous, wilde, fores...
All_key_words_str     1863 detective renard famous wilde forest solv...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-30092301544623547885207845653329099705068919528491472110762920265386536468481, dtype: object
{'_id': ObjectId('6233731aaa5cf772ca915a7d'), 'name': 'cyprus', 'url': 'http://twitter.com/search?q=Cyprus', 'promoted_content': None, 'query': 'Cyprus', 'tweet_volume': 10067, 'created_datetime': datetime.datetime(2022, 3, 17, 17, 42, 50), 'woeid': 44418, 'sentiment_score': 0.2288, 'trend_score': 0.007356913183279743}
 All_key_words_list    [holographic, scallop, 0023, low, poly, hologr...
All_key_words_str     holographic scallop 0023 low poly holographic ...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-7106027673308939733155406626921825671715953579665664670966270461652823441409, dtype: object
{'_id': ObjectId('622fabcdfc95226029d616af'), 'name': 'palace', 'url': 'http://twitter.com/search?q=Palace', 'promoted_content': None, 'query': 'Palace', 'tweet_volume': 43006, 'created_datetime': datetime.datetime(2022, 3, 14, 20, 55, 41), 'woeid': 1, 'sentiment_score': 0.7819, 'trend_score': 0.09795482117321279}
 All_key_words_list    [changdeokgung, palace, changdeokgung, palace,...
All_key_words_str     changdeokgung palace changdeokgung palace king...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-86258965964640701687243968829718411323635577904551749933376039192892496936961, dtype: object
{'_id': ObjectId('622e3927ee4a66d5042f86ca'), 'name': 'maguire', 'url': 'http://twitter.com/search?q=Maguire', 'promoted_content': None, 'query': 'Maguire', 'tweet_volume': 157809, 'created_datetime': datetime.datetime(2022, 3, 13, 14, 0), 'woeid': 1, 'sentiment_score': 0.6713, 'trend_score': 0.29980662807055974}
 All_key_words_list    [celebcard, 93, tobey, maguire, mesmerizer, th...
All_key_words_str     celebcard 93 tobey maguire mesmerizer theme tr...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-25415852838154585030182810174953724094201545459452816665085826165909850423297, dtype: object
{'_id': ObjectId('623842fd40ad6ffd9069b797'), 'name': 'karma', 'url': 'http://twitter.com/search?q=Karma', 'promoted_content': None, 'query': 'Karma', 'tweet_volume': 84738, 'created_datetime': datetime.datetime(2022, 3, 21, 9, 18, 53), 'woeid': 44418, 'sentiment_score': 0.7826, 'trend_score': 0.24307970105826018}
 All_key_words_list    [boundary, 2375, 노상현, south, korea, work, brin...
All_key_words_str     boundary 2375 노상현 south korea work bring good ...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-68800123458035658143408460056219206378254568321398204671677927741989563924481, dtype: object
{'_id': ObjectId('623842fd40ad6ffd9069b797'), 'name': 'karma', 'url': 'http://twitter.com/search?q=Karma', 'promoted_content': None, 'query': 'Karma', 'tweet_volume': 84738, 'created_datetime': datetime.datetime(2022, 3, 21, 9, 18, 53), 'woeid': 44418, 'sentiment_score': 0.7826, 'trend_score': 0.24307970105826018}
 All_key_words_list    [boundary, 2376, 노상현, south, korea, work, brin...
All_key_words_str     boundary 2376 노상현 south korea work bring good ...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-68800123458035658143408460056219206378254568321398204671677927743089075552257, dtype: object
{'_id': ObjectId('623b0f5ea7c0841e994d424f'), 'name': 'rice', 'url': 'http://twitter.com/search?q=Rice', 'promoted_content': None, 'query': 'Rice', 'tweet_volume': 64889, 'created_datetime': datetime.datetime(2022, 3, 23, 12, 15, 26), 'woeid': 44418, 'sentiment_score': -0.0841, 'trend_score': -0.021596992975747745}
 All_key_words_list    [rice, field, environment, dusk, untitled, col...
All_key_words_str     rice field environment dusk untitled collectio...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-4030173576084688656223067553448708629245854475834805770863352343720640905217, dtype: object
{'_id': ObjectId('623842fd40ad6ffd9069b779'), 'name': 'forest', 'url': 'http://twitter.com/search?q=Forest', 'promoted_content': None, 'query': 'Forest', 'tweet_volume': 115516, 'created_datetime': datetime.datetime(2022, 3, 21, 9, 18, 53), 'woeid': 44418, 'sentiment_score': 1.1187, 'trend_score': 0.4736814970692669}
 All_key_words_list    [1864, detective, renard, famous, wilde, fores...
All_key_words_str     1864 detective renard famous wilde forest solv...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-30092301544623547885207845653329099705068919528491472110762920266486048096257, dtype: object
{'_id': ObjectId('625a74193d8b46e9766c7ef9'), 'name': 'jesus', 'url': 'http://twitter.com/search?q=Jesus', 'promoted_content': None, 'query': 'Jesus', 'tweet_volume': 609951, 'created_datetime': datetime.datetime(2022, 4, 16, 7, 45, 29), 'woeid': 44418, 'sentiment_score': 1.4741, 'trend_score': 81.19497269205414}
 All_key_words_list    [jesus, simmons, cryptoguysnft, preparing, nft...
All_key_words_str     jesus simmons cryptoguysnft preparing nft game...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-30041571019036570279696425714306755064417936087066583674697121488131734896641, dtype: object
{'_id': ObjectId('623842fd40ad6ffd9069b797'), 'name': 'karma', 'url': 'http://twitter.com/search?q=Karma', 'promoted_content': None, 'query': 'Karma', 'tweet_volume': 84738, 'created_datetime': datetime.datetime(2022, 3, 21, 9, 18, 53), 'woeid': 44418, 'sentiment_score': 0.7826, 'trend_score': 0.24307970105826018}
 All_key_words_list    [boundary, 2377, 노상현, south, korea, work, brin...
All_key_words_str     boundary 2377 노상현 south korea work bring good ...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-68800123458035658143408460056219206378254568321398204671677927744188587180033, dtype: object
{'_id': ObjectId('623842fd40ad6ffd9069b779'), 'name': 'forest', 'url': 'http://twitter.com/search?q=Forest', 'promoted_content': None, 'query': 'Forest', 'tweet_volume': 115516, 'created_datetime': datetime.datetime(2022, 3, 21, 9, 18, 53), 'woeid': 44418, 'sentiment_score': 1.1187, 'trend_score': 0.4736814970692669}
 All_key_words_list    [small, forest, small, forest, korea, filmed, ...
All_key_words_str     small forest small forest korea filmed young u...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-14350327602552039877887576647231826919280835881303132966518071470950358974465, dtype: object
{'_id': ObjectId('625a74193d8b46e9766c7ee7'), 'name': 'elon', 'url': 'http://twitter.com/search?q=Elon', 'promoted_content': None, 'query': 'Elon', 'tweet_volume': 1025460, 'created_datetime': datetime.datetime(2022, 4, 16, 7, 45, 29), 'woeid': 44418, 'sentiment_score': 0.292, 'trend_score': 27.040132927567115}
 All_key_words_list    [map, art, 135, elon, musk, item, 135, officia...
All_key_words_str     map art 135 elon musk item 135 official map ar...
trend_score                                                        <NA>
matched_trends                                                     <NA>
Name: 0x495f947276749ce646f68ac8c248420045cb7b5e-110044771230368441551571992070040963530623495929530335175865263817154854125569, dtype: object

display items that have trends that were matched

In [114]:
# get items that only have a trend_score (greater than zero, to not get negative ranked sentiment items at all)
  # This condition depends on the implementation (to to find a score/ method to rank these values in the middle with zeros (item-to-item matches? based on categorical content in trends/ trending items?), 
  # because whatever trend it is, even negative sentiment might be better than no sentiment - this affects precision or recall)
  # trending_df = df[df["trend_score"] > 0 ]
trending_df = df[df['trend_score'] != 0]

trending_df.head()

,All_key_words_list,All_key_words_str,trend_score,matched_trends
reference_id,,,,
0x495f947276749ce646f68ac8c248420045cb7b5e-107628504515518689987342262222228454948876366026517717055271263417611411521537,"[old, paint, 128, elliot, page, mesmerizer, th...",old paint 128 elliot page mesmerizer theme tra...,0.516061,[elliot]
0x495f947276749ce646f68ac8c248420045cb7b5e-82256463676502440146450897687557167086816165697899976211264002330492657467492,"[nasi, lemak, vassal, card, spicy, rice, meal,...",nasi lemak vassal card spicy rice meal egg pea...,-0.021597,[rice]
0x495f947276749ce646f68ac8c248420045cb7b5e-4681315841332783359872218394132880425029351767574165810619795540587963219969,"[amandelele, africa]",amandelele africa,5.797412,[africa]
0xd85ebb24bc0c2fcd6901cc9ae7409e41d4a9e0a3-342,"[haze, monkey, society, genesis, nft, haze, mo...",haze monkey society genesis nft haze monkey so...,5.797412,[africa]
0xd85ebb24bc0c2fcd6901cc9ae7409e41d4a9e0a3-341,"[haze, monkey, society, genesis, nft, haze, mo...",haze monkey society genesis nft haze monkey so...,5.797412,[africa]

### Get Trends based Recommendations sorted by `trend_score`

In [115]:
def trends_based_recommendations():
  # sort dataframe based on trend_score
  top_trending_df = trending_df.sort_values(by=['trend_score'], ascending=False)

  return top_trending_df

## Testing

In [116]:
# content_based_recommendations('0x495f947276749ce646f68ac8c248420045cb7b5e-57422959511997337577873730268633988669226471548944456734432444570123223695361')

In [117]:
# trends_based_recommendations('0x495f947276749ce646f68ac8c248420045cb7b5e-57422959511997337577873730268633988669226471548944456734432444570123223695361')

top_trending_nfts_df = trends_based_recommendations()

top_trending_nfts_df.head()

,All_key_words_list,All_key_words_str,trend_score,matched_trends
reference_id,,,,
0x495f947276749ce646f68ac8c248420045cb7b5e-30041571019036570279696425714306755064417936087066583674697121488131734896641,"[jesus, simmons, cryptoguysnft, preparing, nft...",jesus simmons cryptoguysnft preparing nft game...,81.194973,[jesus]
0x495f947276749ce646f68ac8c248420045cb7b5e-25415852838154585030182810174953724094201545459452816665085826161511803912193,"[celebcard, 9, billie, eilish, mesmerizer, the...",celebcard 9 billie eilish mesmerizer theme tra...,61.35276,[billie]
0x495f947276749ce646f68ac8c248420045cb7b5e-94916783746142258917689322291875902080657954662840061252830161925292293095425,"[triangles, 109, rihanna, mesmerizer, theme, t...",triangles 109 rihanna mesmerizer theme traits ...,53.956252,[rihanna]
0x495f947276749ce646f68ac8c248420045cb7b5e-30041571019036570279696425714306755064417936087066583674697121415563967463425,"[christian, mathews, cryptoguysnft, preparing,...",christian mathews cryptoguysnft preparing nft ...,35.474189,[christian]
0x495f947276749ce646f68ac8c248420045cb7b5e-107628504515518689987342262222228454948876366026517717055271263433004574310401,"[midnight, art, 2, elon, musk, mesmerizer, the...",midnight art 2 elon musk mesmerizer theme trai...,27.040133,[elon]

In [118]:
top_trending_nfts_df

,All_key_words_list,All_key_words_str,trend_score,matched_trends
reference_id,,,,
0x495f947276749ce646f68ac8c248420045cb7b5e-30041571019036570279696425714306755064417936087066583674697121488131734896641,"[jesus, simmons, cryptoguysnft, preparing, nft...",jesus simmons cryptoguysnft preparing nft game...,81.194973,[jesus]
0x495f947276749ce646f68ac8c248420045cb7b5e-25415852838154585030182810174953724094201545459452816665085826161511803912193,"[celebcard, 9, billie, eilish, mesmerizer, the...",celebcard 9 billie eilish mesmerizer theme tra...,61.35276,[billie]
0x495f947276749ce646f68ac8c248420045cb7b5e-94916783746142258917689322291875902080657954662840061252830161925292293095425,"[triangles, 109, rihanna, mesmerizer, theme, t...",triangles 109 rihanna mesmerizer theme traits ...,53.956252,[rihanna]
0x495f947276749ce646f68ac8c248420045cb7b5e-30041571019036570279696425714306755064417936087066583674697121415563967463425,"[christian, mathews, cryptoguysnft, preparing,...",christian mathews cryptoguysnft preparing nft ...,35.474189,[christian]
0x495f947276749ce646f68ac8c248420045cb7b5e-107628504515518689987342262222228454948876366026517717055271263433004574310401,"[midnight, art, 2, elon, musk, mesmerizer, the...",midnight art 2 elon musk mesmerizer theme trai...,27.040133,[elon]
0x495f947276749ce646f68ac8c248420045cb7b5e-107628504515518689987342262222228454948876366026517717055271263434104085938177,"[bobblehead, 3, elon, musk, mesmerizer, theme,...",bobblehead 3 elon musk mesmerizer theme traits...,27.040133,[elon]
0x495f947276749ce646f68ac8c248420045cb7b5e-110044771230368441551571992070040963530623495929530335175865263817154854125569,"[map, art, 135, elon, musk, item, 135, officia...",map art 135 elon musk item 135 official map ar...,27.040133,[elon]
0xd85ebb24bc0c2fcd6901cc9ae7409e41d4a9e0a3-341,"[haze, monkey, society, genesis, nft, haze, mo...",haze monkey society genesis nft haze monkey so...,5.797412,[africa]
0xd85ebb24bc0c2fcd6901cc9ae7409e41d4a9e0a3-342,"[haze, monkey, society, genesis, nft, haze, mo...",haze monkey society genesis nft haze monkey so...,5.797412,[africa]
0x495f947276749ce646f68ac8c248420045cb7b5e-7491531393923003805044818105774040167028060283580351255649420436864434700289,"[004, drought, dust, africa, nft, dust, africa...",004 drought dust africa nft dust africa proudl...,5.797412,[africa]
0xd85ebb24bc0c2fcd6901cc9ae7409e41d4a9e0a3-346,"[haze, monkey, society, genesis, nft, haze, mo...",haze monkey society genesis nft haze monkey so...,5.797412,[africa]
0xd85ebb24bc0c2fcd6901cc9ae7409e41d4a9e0a3-345,"[haze, monkey, society, genesis, nft, haze, mo...",haze monkey society genesis nft haze monkey so...,5.797412,[africa]
0x495f947276749ce646f68ac8c248420045cb7b5e-33667053789437555920986692599124277764649475007205440601468718221139055214593,"[house, lake, 2321, street, photographynfts, c...",house lake 2321 street photographynfts collect...,5.797412,[africa]
0x495f947276749ce646f68ac8c248420045cb7b5e-33667053789437555920986692599124277764649475007205440601468718220039543586817,"[duck, family, 11021, street, photographynfts,...",duck family 11021 street photographynfts colle...,5.797412,[africa]
0x495f947276749ce646f68ac8c248420045cb7b5e-4681315841332783359872218394132880425029351767574165810619795540587963219969,"[amandelele, africa]",amandelele africa,5.797412,[africa]
0x495f947276749ce646f68ac8c248420045cb7b5e-54913028823869484484969640998172385576008206379346437203989969339057359028225,"[moonshot, s1, ep, 5, euphoria, moonshot, s1, ...",moonshot s1 ep 5 euphoria moonshot s1 ep 5 eup...,2.388469,[euphoria]
0x495f947276749ce646f68ac8c248420045cb7b5e-94916783746142258917689322291875902080657954662840061252830161918695223328769,"[ether, art, 39, cristiano, ronaldo, mesmerize...",ether art 39 cristiano ronaldo mesmerizer them...,2.207758,[ronaldo]
0x495f947276749ce646f68ac8c248420045cb7b5e-107628504515518689987342262222228454948876366026517717055271263437402620821505,"[stars, poster, 09, cristiano, ronaldo, mesmer...",stars poster 09 cristiano ronaldo mesmerizer t...,2.207758,[ronaldo]
0x495f947276749ce646f68ac8c248420045cb7b5e-107628504515518689987342262222228454948876366026517717055271263436303109193729,"[stars, poster, 08, cristiano, ronaldo, mesmer...",stars poster 08 cristiano ronaldo mesmerizer t...,2.207758,[ronaldo]
0x495f947276749ce646f68ac8c248420045cb7b5e-107628504515518689987342262222228454948876366026517717055271263417611411521537,"[old, paint, 128, elliot, page, mesmerizer, th...",old paint 128 elliot page mesmerizer theme tra...,0.516061,[elliot]
0x495f947276749ce646f68ac8c248420045cb7b5e-77674177141111627268613029660198545550869301162278412343025582587737142198273,"[upside, sitting, cafe, thought, instead, read...",upside sitting cafe thought instead reading bo...,0.509272,[iran]
0x495f947276749ce646f68ac8c248420045cb7b5e-30092301544623547885207845653329099705068919528491472110762920264287024840705,"[1862, detective, renard, famous, wilde, fores...",1862 detective renard famous wilde forest solv...,0.473681,[forest]
0x495f947276749ce646f68ac8c248420045cb7b5e-30305723071712888013025707612312918974418223904717978944673020007405775224833,"[slime, eye, 7, report, 592, 1308, year, birth...",slime eye 7 report 592 1308 year birth star bo...,0.473681,[forest]
0x495f947276749ce646f68ac8c248420045cb7b5e-30092301544623547885207845653329099705068919528491472110762920266486048096257,"[1864, detective, renard, famous, wilde, fores...",1864 detective renard famous wilde forest solv...,0.473681,[forest]
0x495f947276749ce646f68ac8c248420045cb7b5e-14350327602552039877887576647231826919280835881303132966518071470950358974465,"[small, forest, small, forest, korea, filmed, ...",small forest small forest korea filmed young u...,0.473681,[forest]
0x495f947276749ce646f68ac8c248420045cb7b5e-30092301544623547885207845653329099705068919528491472110762920265386536468481,"[1863, detective, renard, famous, wilde, fores...",1863 detective renard famous wilde forest solv...,0.473681,[forest]
0x495f947276749ce646f68ac8c248420045cb7b5e-79598145459366138456148796052825547483993807520203766226242728957798908952577,"[rimuru, tempest, leader, tempest, forest, sha...",rimuru tempest leader tempest forest shaker ve...,0.473681,[forest]
0x495f947276749ce646f68ac8c248420045cb7b5e-25415852838154585030182810174953724094201545459452816665085826165909850423297,"[celebcard, 93, tobey, maguire, mesmerizer, th...",celebcard 93 tobey maguire mesmerizer theme tr...,0.299807,[maguire]
0x495f947276749ce646f68ac8c248420045cb7b5e-110044771230368441551571992070040963530623495929530335175865263803960714592257,"[map, art, 190, zendaya, tom, holland, item, 1...",map art 190 zendaya tom holland item 190 offic...,0.289647,[zendaya]
0x06012c8cf97bead5deae237070f9587f8e7a266d-439146,"[zendaya, good, morning, zendaya, enjoy, trick...",zendaya good morning zendaya enjoy tricking ba...,0.289647,[zendaya]
0x495f947276749ce646f68ac8c248420045cb7b5e-68800123458035658143408460056219206378254568321398204671677927739790540668929,"[boundary, 2373, 노상현, south, korea, work, brin...",boundary 2373 노상현 south korea work bring good ...,0.24308,[karma]
0x495f947276749ce646f68ac8c248420045cb7b5e-68800123458035658143408460056219206378254568321398204671677927741989563924481,"[boundary, 2375, 노상현, south, korea, work, brin...",boundary 2375 노상현 south korea work bring good ...,0.24308,[karma]
0x495f947276749ce646f68ac8c248420045cb7b5e-68800123458035658143408460056219206378254568321398204671677927734292982530049,"[boundary, 2367, 노상현, south, korea, work, brin...",boundary 2367 노상현 south korea work bring good ...,0.24308,[karma]
0x495f947276749ce646f68ac8c248420045cb7b5e-68800123458035658143408460056219206378254568321398204671677927736492005785601,"[boundary, 2370, 노상현, south, korea, work, brin...",boundary 2370 노상현 south korea work bring good ...,0.24308,[karma]
0x495f947276749ce646f68ac8c248420045cb7b5e-68800123458035658143408460056219206378254568321398204671677927737591517413377,"[boundary, 2371, 노상현, south, korea, work, brin...",boundary 2371 노상현 south korea work bring good ...,0.24308,[karma]
0x495f947276749ce646f68ac8c248420045cb7b5e-68800123458035658143408460056219206378254568321398204671677927735392494157825,"[boundary, 2369, 노상현, south, korea, work, brin...",boundary 2369 노상현 south korea work bring good ...,0.24308,[karma]
0x495f947276749ce646f68ac8c248420045cb7b5e-68800123458035658143408460056219206378254568321398204671677927738691029041153,"[boundary, 2372, 노상현, south, korea, work, brin...",boundary 2372 노상현 south korea work bring good ...,0.24308,[karma]
0x495f947276749ce646f68ac8c248420045cb7b5e-68800123458035658143408460056219206378254568321398204671677927740890052296705,"[boundary, 2374, 노상현, south, korea, work, brin...",boundary 2374 노상현 south korea work bring good ...,0.24308,[karma]
0x495f947276749ce646f68ac8c248420045cb7b5e-68800123458035658143408460056219206378254568321398204671677927744188587180033,"[boundary, 2377, 노상현, south, korea, work, brin...",boundary 2377 노상현 south korea work bring good ...,0.24308,[karma]
0x495f947276749ce646f68ac8c248420045cb7b5e-68800123458035658143408460056219206378254568321398204671677927743089075552257,"[boundary, 2376, 노상현, south, korea, work, brin...",boundary 2376 노상현 south korea work bring good ...,0.24308,[karma]
0x495f947276749ce646f68ac8c248420045cb7b5e-86258965964640701687243968829718411323635577904551749933376039192892496936961,"[changdeokgung, palace, changdeokgung, palace,...",changdeokgung palace changdeokgung palace king...,0.097955,[palace]
0x495f947276749ce646f68ac8c248420045cb7b5e-87097006728074405550105794430242480615394971290040881095948994330785103216641,"[inner, light, 010, romero, simpson, photo, co...",inner light 010 romero simpson photo collectio...,0.070162,[romero]
0x495f947276749ce646f68ac8c248420045cb7b5e-94916783746142258917689322291875902080657954662840061252830161924192781467649,"[oil, portrait, 100, david, beckham, mesmerize...",oil portrait 100 david beckham mesmerizer them...,0.030586,[beckham]
0x495f947276749ce646f68ac8c248420045cb7b5e-7106027673308939733155406626921825671715953579665664670966270461652823441409,"[holographic, scallop, 0023, low, poly, hologr...",holographic scallop 0023 low poly holographic ...,0.007357,[cyprus]
0x93a59e8300f3186744d6203b35211635ad5da45d-2283,"[queens, kings, traits, queens, kings, overthr...",queens kings traits queens kings overthrow hie...,0.000282,[royals]
0xa1029ea8a5a1d2add0eff2c92097a89a593f0025-1780,"[queens, kings, traits, queens, kings, overthr...",queens kings traits queens kings overthrow hie...,0.000282,[royals]
0xcf3d707e2b3b3c76aa08f20afb7887c4114f5703-170,"[queens, kings, traits, queens, kings, overthr...",queens kings traits queens kings overthrow hie...,0.000282,[royals]
0x3badda62fe3ee137548eb5ca0df1be0b2f960418-1307,"[queens, kings, traits, queens, kings, overthr...",queens kings traits queens kings overthrow hie...,0.000282,[royals]
0x5567cc781b169ed6e930b407ab038e7a8789dfd7-1816,"[queens, kings, traits, queens, kings, overthr...",queens kings traits queens kings overthrow hie...,0.000282,[royals]
0xda34cb1e8f9e5616b4d0ff3cc5716d8aca7ae66f-202,"[queens, kings, traits, queens, kings, overthr...",queens kings traits queens kings overthrow hie...,0.000282,[royals]
0xbd5bd01e9445d24d83e8607ac0a64d71c9d36933-105,"[queens, kings, traits, queens, kings, overthr...",queens kings traits queens kings overthrow hie...,0.000282,[royals]
0x46ad682c4286d5ac4b54c02739cb25336a774357-1684,"[queens, kings, traits, queens, kings, overthr...",queens kings traits queens kings overthrow hie...,0.000282,[royals]
0x495f947276749ce646f68ac8c248420045cb7b5e-82256463676502440146450897687557167086816165697899976211264002330492657467492,"[nasi, lemak, vassal, card, spicy, rice, meal,...",nasi lemak vassal card spicy rice meal egg pea...,-0.021597,[rice]
0x495f947276749ce646f68ac8c248420045cb7b5e-4030173576084688656223067553448708629245854475834805770863352343720640905217,"[rice, field, environment, dusk, untitled, col...",rice field environment dusk untitled collectio...,-0.021597,[rice]
0x495f947276749ce646f68ac8c248420045cb7b5e-21501015388731809064841095921007249806046747253819384677393285554247835844609,"[到底要带谁回家过年呢, going, home, new, year, list, boy...",到底要带谁回家过年呢 going home new year list boyfriends...,-0.426166,[boyfriends]

In [119]:
top_trending_nfts_df.shape[0]

55

## Evaluation

create a dataframe with created_datetime (x axis), trend_count (y-axis), new_trend_count/new_matched_count (y-axis)

Do this for both matched trends and all trends separately.

In [120]:
graph_trends_data = []

# Create the pandas DataFrame
graph_trends_df = pd.DataFrame(graph_trends_data, columns = ['created_datetime', 'trend_count', 'total_matched_count', 'new_matched_count'])

graph_trends_df.head()

# loop through all available twitter_trends docs in mongodb
# for trend in twitter_trends:
#   graph_trends_df.append()

Empty DataFrame
Columns: [created_datetime, trend_count, total_matched_count, new_matched_count]
Index: []

Take all trends into a dataframe and then try to filter by unique date etc

In [121]:
# eval_trends_df = pd.DataFrame(twitter_trends, columns=['name','created_datetime', ''])
all_trends_df = pd.DataFrame(twitter_trends)

all_trends_df.head()

,_id,name,url,promoted_content,query,tweet_volume,created_datetime,woeid,sentiment_score,trend_score
0,622e388aee4a66d5042f86a4,sam levinson,http://twitter.com/search?q=%22sam+levinson%22,None,%22sam+levinson%22,93293.0,2022-02-28 13:00:00,1,1.0000,0.192665
1,622e388aee4a66d5042f869b,28şubat,http://twitter.com/search?q=%2328%C5%9Eubat,None,%2328%C5%9Eubat,42633.0,2022-02-28 13:00:00,1,1.0000,0.088044
2,622e388aee4a66d5042f869d,andalucía,http://twitter.com/search?q=Andaluc%C3%ADa,None,Andaluc%C3%ADa,39283.0,2022-02-28 13:00:00,1,0.5047,0.040944
3,622e388aee4a66d5042f86a0,callin_mv_out,http://twitter.com/search?q=%23Callin_MV_Out,None,%23Callin_MV_Out,23107.0,2022-02-28 13:00:00,1,1.0000,0.047720
4,622e388aee4a66d5042f86a3,jules,http://twitter.com/search?q=Jules,None,Jules,100974.0,2022-02-28 13:00:00,1,0.8782,0.183129

In [122]:
# all_trends_df.sort_values(by='created_datetime')
# all_trends_df

# the trends are anyway sorted by created_datetime because they were entered in order

For each row in the dataframe, have an incrementer for the number of trends per day (trend_count) 
using the trends of each day, find the number of matches (total_matched_items_count	, new_matched_items_count) with the nft dataset.

extra: insert each object _id into an array to reference these later by date? - can do this directly with mongodb as well. Kind of unnecessary.

In [123]:
all_trends_df.dtypes

_id                         object
name                        object
url                         object
promoted_content            object
query                       object
tweet_volume               float64
created_datetime    datetime64[ns]
woeid                        int64
sentiment_score            float64
trend_score                float64
dtype: object

In [124]:
# eval_trends_df = pd.DataFrame(graph_trends_data, columns = ['created_datetime', 'trend_count', 'total_matched_count', 'new_matched_count'])
#  TODO: have a dictionary instead of a dataframe to record key= created_datetime, value= {'trend_count', 'total_matched_items_count', 'new_matched_items_count'}
eval_trends_count_dict = {}
trends_per_datetime = {}  # datetime, trends[]

# first extract created_datetime 
unique_created_datetimes = all_trends_df['created_datetime'].unique()
# print(unique_created_datetimes)

# then filter each created_time to get number of records (trends_count) per datetime
for datetime in unique_created_datetimes:
  trends_df = all_trends_df[all_trends_df['created_datetime'] == datetime]
  # print(trends_df.values.tolist())
  trends_per_datetime[str(datetime)] = trends_df.values.tolist()
  val_eval_trends_count_dict = {'trend_count': len(trends_df.values.tolist())}
  eval_trends_count_dict[str(datetime)] = val_eval_trends_count_dict

pp.pprint(eval_trends_count_dict)

{'2022-02-28T13:00:00.000000000': {'trend_count': 50},
 '2022-03-13T14:00:00.000000000': {'trend_count': 50},
 '2022-03-13T18:37:20.000000000': {'trend_count': 50},
 '2022-03-14T07:40:19.000000000': {'trend_count': 50},
 '2022-03-14T20:55:41.000000000': {'trend_count': 50},
 '2022-03-15T09:32:37.000000000': {'trend_count': 48},
 '2022-03-15T13:32:32.000000000': {'trend_count': 48},
 '2022-03-17T09:21:26.000000000': {'trend_count': 39},
 '2022-03-17T17:42:50.000000000': {'trend_count': 48},
 '2022-03-21T09:18:53.000000000': {'trend_count': 48},
 '2022-03-22T12:43:01.000000000': {'trend_count': 48},
 '2022-03-23T12:15:26.000000000': {'trend_count': 48},
 '2022-04-16T07:45:29.000000000': {'trend_count': 50},
 '2022-04-17T10:33:42.000000000': {'trend_count': 50}}

In [125]:
matched_trends_set = set() # used to record matched trends with items
#METHOD 3
# iterating through items dataframe with trend_scores (only these items will eventually get matched anyway)
for index, row in trending_df.iterrows():
  # get row['matched_trends']
  matched_trends_per_item = row['matched_trends']

  for matched_trend in matched_trends_per_item:
    # filter all_trends_df by matched_trends
    filtered_trends_df = all_trends_df[all_trends_df['name'] == matched_trend]
    # print(filtered_trends_df.head())

    # get created_datetime of matched_trend
    datetime = str(filtered_trends_df.iloc[0]['created_datetime'].to_numpy()) # https://pandas.pydata.org/docs/reference/api/pandas.Timestamp.to_numpy.html
    # print(type(datetime))
    # print(datetime)

    # print(eval_trends_count_dict[datetime])
    # print(eval_trends_count_dict.get(datetime))

    updated_eval_value_dict = eval_trends_count_dict[datetime]
    
    total_matched_items_count = updated_eval_value_dict.get('total_matched_items_count')

    if total_matched_items_count:
      updated_eval_value_dict['total_matched_items_count'] = total_matched_items_count + 1
    else:
      updated_eval_value_dict['total_matched_items_count'] = 1

    if matched_trend not in matched_trends_set:
      new_matched_items_count = updated_eval_value_dict.get('new_matched_items_count')

      if new_matched_items_count:
        updated_eval_value_dict['new_matched_items_count'] = new_matched_items_count + 1
      else:
        updated_eval_value_dict['new_matched_items_count'] = 1

      matched_trends_set.add(matched_trend)
    
    # update eval_trends_count_dict for each created_datetime
    eval_trends_count_dict[datetime] = updated_eval_value_dict

pp.pprint(eval_trends_count_dict)





# ------ deletable
#METHOD 2
  # for created_datetime in trends_per_datetime:
  #   trends = trends_per_datetime[created_datetime]  # get trends obj arr of each day

  #   for trend_obj_arr in trends:
  #     if trend_obj_arr[1] in row['All_key_words_list']:
  #       print(trend_obj_arr)


#ATTEMPT 1
# for index, row in all_trends_df.iterrows():
#   created_datetime = row['created_datetime']
  # trend_name = row['name']

# matches with the items dataset - TODO separately
# if trend_name in matched_trends_set:
  # just increment the total_matched_count
# else:
  # increment => trend_count
  # , new_matched_count, total_matched_count

  # add trend to matched_trends_set

{'2022-02-28T13:00:00.000000000': {'new_matched_items_count': 3,
                                   'total_matched_items_count': 4,
                                   'trend_count': 50},
 '2022-03-13T14:00:00.000000000': {'new_matched_items_count': 3,
                                   'total_matched_items_count': 5,
                                   'trend_count': 50},
 '2022-03-13T18:37:20.000000000': {'trend_count': 50},
 '2022-03-14T07:40:19.000000000': {'trend_count': 50},
 '2022-03-14T20:55:41.000000000': {'new_matched_items_count': 1,
                                   'total_matched_items_count': 1,
                                   'trend_count': 50},
 '2022-03-15T09:32:37.000000000': {'trend_count': 48},
 '2022-03-15T13:32:32.000000000': {'trend_count': 48},
 '2022-03-17T09:21:26.000000000': {'new_matched_items_count': 1,
                                   'total_matched_items_count': 1,
                                   'trend_count': 39},
 '2022-03-17T17:42:50.000000000': {'new_matched_items_count': 1,
                                   'total_matched_items_count': 1,
                                   'trend_count': 48},
 '2022-03-21T09:18:53.000000000': {'new_matched_items_count': 2,
                                   'total_matched_items_count': 16,
                                   'trend_count': 48},
 '2022-03-22T12:43:01.000000000': {'new_matched_items_count': 1,
                                   'total_matched_items_count': 8,
                                   'trend_count': 48},
 '2022-03-23T12:15:26.000000000': {'new_matched_items_count': 2,
                                   'total_matched_items_count': 3,
                                   'trend_count': 48},
 '2022-04-16T07:45:29.000000000': {'new_matched_items_count': 5,
                                   'total_matched_items_count': 14,
                                   'trend_count': 50},
 '2022-04-17T10:33:42.000000000': {'new_matched_items_count': 2,
                                   'total_matched_items_count': 2,
                                   'trend_count': 50}}

add 0s to dates that have no matches

show how items that have the top 20 trends score varies with time

In [ ]:
# # importing packages
# import seaborn as sns
# import matplotlib.pyplot as plt

# # loading dataset
# data = graph_trends_data

# # draw lineplot
# sns.lineplot(x="sepal_length", y="sepal_width", data=data)
# plt.show()

The trends can be filtered to use only nouns

TODO: display trends with a trend score in a separate dashboard - creators can try to come up with the best possible combinations of trends in items

TODO: Show how items that have a trend_score, changes it's trend_score with time - to show how it decreases with time